sebastian-heinz/Arrowgene.DragonsDogmaOnline

- .vscode/extensions.json
- .vscode/launch.json
- Arrowgene.Ddon.Shared/AssetRepository.cs
Added a retry loop in order to prevent the server from crashing when the enemy set CSV to reload is still locked by some other process
> Exception handling when reloading enemy set CSV

- Arrowgene.Ddon.GameServer/Handler/ContextGetSetContextHandler.cs
- Arrowgene.Ddon.GameServer/Handler/StageAreaChangeHandler.cs
- Arrowgene.Ddon.Shared/Entity/EntitySerializer.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CContextSetContextBaseNtc.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CInstance_13_42_16_Ntc.cs
- Arrowgene.Ddon.Shared/Network/PacketId.cs
In order to avoid enemies not spawning, the delivery of
S2CContextSetContextBaseNtc was commented out.
However this had the side effect of human enemies not spawning at all.
To have the best of both worlds, we send S2CInstance_13_42_16_Ntc, as
it's been noticed on the pcaps, when entering a safe area (White Dragon
Temple) so the context gets reset and enemies in the field respawn.
> Context resetting when entering safe areas

- Arrowgene.Ddon.GameServer/Handler/SkillGetLearnedSkillListHandler.cs
EX skills must be Lv 1 otherwise they do 0 dmg
> Lv 1 EX skills in SkillGetLearnedSkillListHandler

- Arrowgene.Ddon.GameServer/Handler/PawnJoinPartyMypawnHandler.cs
Empty slots still had to be sent when serializing as CDataContextEquipData
> Fixed pawns not showing up

- Arrowgene.Ddon.GameServer/Party/PartyManager.cs
When the ID pool is exhauested and a new party is created, a function is run that checks all the connected client's parties and rebuilds the party ID pool with that information. Far from ideal but seems to do the job for the time being.
> Workaround for the party ID pool exhausting over time.

- Arrowgene.Ddon.Database/IDatabase.cs
- Arrowgene.Ddon.Database/Sql/Core/DdonSqlDbCharacterCommon.cs
- Arrowgene.Ddon.Database/Sql/Core/DdonSqlDbLearnedAbility.cs
- Arrowgene.Ddon.Database/Sql/Core/DdonSqlDbLearnedCustomSkill.cs
- Arrowgene.Ddon.GameServer/Characters/JobManager.cs
- Arrowgene.Ddon.GameServer/Handler/SkillLearnSkillHandler.cs
The problem was caused by INSERT OR REPLACE in the learned skill/augs tables triggering the ON DELETE CASCADE in the equipped skills/augs tables
> Fixed equipped skills/augs being removed after upgrading them

- Arrowgene.Ddon.GameServer/Handler/ConnectionLoginHandler.cs
- Arrowgene.Ddon.LoginServer/Handler/ClientLoginHandler.cs
This fixes the "Return to Title" issue since the token was different it would either throw an error or generate a new account (in both required or not account from the config).
Login token is only regenerated and updated on each logging in through the launcher.
Also increased the login token lifespan so it can be used for longer (a week if the person doesn't log out).
> Commented Game Token Overwritting Login Token

- Arrowgene.Ddon.GameServer/Characters/JobManager.cs
Intead of JPs from the active job
> Unlocking skills/augs now substract JP from the unlocked skill/aug's job

- Arrowgene.Ddon.Database/IDatabase.cs
- Arrowgene.Ddon.Database/Sql/Core/DdonSqlDbEquipItem.cs
- Arrowgene.Ddon.GameServer/Characters/EquipManager.cs
> Fix exception swapping equipment w a full item bag

- Arrowgene.Ddon.GameServer/GatheringItems/InstanceItemManager.cs
- Arrowgene.Ddon.GameServer/Handler/InstanceEnemyKillHandler.cs
> Drop item bags no longer show up when spawning empty

- Arrowgene.Ddon.Shared/Files/Assets/EnemySpawn.json
Adds the rest of the monsters loot tables.
Stuff may have been missed, if anyone notices anything feel free to ping me @meecube in discord 👍 
don't really have a good method for comparing, besides trying to use common terms n such.
Some monsters sharing tables is problematic aswell, I saved some time by not making some needlessly unique, but half-way through decided that's too restrictive, so whenever the day/night pass happens, I'll retro-fit the shared tables into unique ones 👍
> Remaining Monster Loottables Assigned

- Arrowgene.Ddon.Shared/Files/Assets/EnemySpawn.json
Sorry for the mini-PR, the info for the 2nd item in Blaze Harpy's pool came just a smidge too late to sneak the commit into my prior PR lol
This adds the missing item to the Blaze Harpy loottable, and thus removes the "INCONCLUSIVE" status.
> Completed Blaze Harpy LootTable

- Arrowgene.Ddon.GameServer/DdonGameServer.cs
- Arrowgene.Ddon.GameServer/Handler/CraftSkillAnalyzeHandler.cs
- Arrowgene.Ddon.Shared/Entity/EntitySerializer.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/C2SCraftSkillAnalyzeReq.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CCraftSkillAnalyzeRes.cs
- Arrowgene.Ddon.Shared/Entity/Structure/CDataCraftSkillAnalyzeResult.cs
Added a handler for crafting performance analysis to stop common hangs in the crafting menu. The server will simply reply back with a list of no results, resolving the client timeout issue.
> feat: Add empty handler for craft skill analyze option

- Arrowgene.Ddon.Cli/Command/Packet/PacketCommandException.cs
- Arrowgene.Ddon.Cli/Command/Packet/PacketServerType.cs
- Arrowgene.Ddon.Cli/Command/Packet/PcapPacket.cs
- Arrowgene.Ddon.Cli/Command/PacketCommand.cs
- Arrowgene.Ddon.Server/Network/PacketFactory.cs
- Arrowgene.Ddon.Shared/Network/ServerType.cs
- Arrowgene.Ddon.Test/Cli/Command/PacketCommandTest.cs
- Arrowgene.Ddon.Test/TestFiles/stream51-marked.pcapng_tcp-stream-11.yaml
- Arrowgene.Ddon.Test/TestFiles/stream85-marked.pcapng_tcp-stream-11_edge_case.yaml
When a packet header is read for its datasize and it is valid, but the buffer no longer contains data, assume it's a split data packet. Add unit tests for these edge cases.
Throw errors instead of graciously failing.
> Add support for stream51 and stream85 package decryption.

- Arrowgene.Ddon.Database/Files/Database/Script/schema_sqlite.sql
- Arrowgene.Ddon.Database/Sql/Core/DdonSqlDbCharacterCommon.cs
- deploy/mariadb/schema_mariadb.sql
- deploy/postgresql/schema_postgres.sql
Since the dragon force augment mechanic was implemented, the jewelry_slot_num field in the DB is no longer used, so remove it.
> refactor: Remove unused jewelry_slot_num field

- Arrowgene.Ddon.GameServer/Handler/LobbyLobbyDataMsgHandler.cs
- Arrowgene.Ddon.GameServer/Handler/RpcHandler.cs
- Arrowgene.Ddon.Shared/Entity/RpcPacketStructure/IRpcPacket.cs
- Arrowgene.Ddon.Shared/Entity/RpcPacketStructure/RpcHeartbeatPacket.cs
- Arrowgene.Ddon.Shared/Entity/RpcPacketStructure/RpcLoginPacket.cs
- Arrowgene.Ddon.Shared/Entity/RpcPacketStructure/RpcPacketBase.cs
- Arrowgene.Ddon.Shared/Entity/RpcPacketStructure/RpcPacketHeader.cs
- Arrowgene.Ddon.Shared/Model/RpcMessageId.cs
- Arrowgene.Ddon.Shared/Model/RpcPacketType.cs
- Added a new handler for RPC packet contents.
- Identified a few new RPC packets and added their definitions which can be used by the new handler.
- Identified new fields in existing packet being parsed.
> feat: Update RPC packet handling

- Arrowgene.Ddon.Cli/Command/PacketCommand.cs
- Arrowgene.Ddon.Shared/Network/StructurePacket.cs
- Arrowgene.Ddon.Test/Cli/Command/PacketCommandTest.cs
Add support for structure dumps.
Add support for customizing byte dump separator and prefix.
This also deactivates all customizations by default and expects the user to provide the switches.
> Add more customization options for packet command.

- Arrowgene.Ddon.Database/Files/Database/Script/schema_sqlite.sql
- Arrowgene.Ddon.Database/Sql/Core/DdonSqlDbCharacterCommon.cs
Removed stats related to gain params which are now tracked by the dragon force augmentation table.
> refactor: Remove unused stats from the DB

- Arrowgene.Ddon.Server/ServerLogger.cs
Added a newline so the start of the hexdump starts inline with the rest of the hexdump instead of on the same line as the information message.
> fix: Add missing newline to Logger.Hex

- Arrowgene.Ddon.Database/Files/Database/Script/schema_sqlite.sql
- Arrowgene.Ddon.Database/Sql/Core/DdonSqlDbCharacterCommon.cs
- Arrowgene.Ddon.GameServer/Characters/CharacterManager.cs
- Arrowgene.Ddon.GameServer/Handler/LobbyLobbyLeaveHandler.cs
- Arrowgene.Ddon.GameServer/Handler/RpcHandler.cs
- Arrowgene.Ddon.Shared/Entity/RpcPacketStructure/IRpcPacket.cs
- Arrowgene.Ddon.Shared/Entity/RpcPacketStructure/RpcHeartbeatPacket.cs
- Arrowgene.Ddon.Shared/Entity/RpcPacketStructure/RpcLoginPacket.cs
- Arrowgene.Ddon.Shared/Entity/RpcPacketStructure/RpcPacketBase.cs
- Arrowgene.Ddon.Shared/Entity/RpcPacketStructure/RpcPacketHeader.cs
- Arrowgene.Ddon.Shared/Model/CharacterCommon.cs
- Arrowgene.Ddon.Shared/Model/RpcId.cs
When a user logs out or disconnects, the disconnect notification is raised.
When this happens, the current value of green and white HP is stored in the
DB. This value will then be used the next time the character is logged into.
When the user purchases an upgrade at the white dragon, HP and Stamina are
refilled to the max value.
> feat: Track HP and Stamina properly after upgrades and logout

- Arrowgene.Ddon.GameServer/Handler/SkillGetAcquirableAbilityListHandler.cs
- Arrowgene.Ddon.GameServer/Handler/SkillLearnPawnAbilityHandler.cs
- Arrowgene.Ddon.GameServer/Handler/SkillSetPawnAbilityHandler.cs
Fixed an issue where the lists for pawns were not searching in the correct location for skills. If a user tries to buy or equip a secret ability on a pawn it would cause a null pointer exception.
> fix: Fix issue with secret abilities on pawns

- Arrowgene.Ddon.GameServer/Characters/CharacterManager.cs
If the player or pawn is in a party, update all party members of the new stats.
> fix: Update all party members when BO upgrade is purchased.

- Arrowgene.Ddon.GameServer/Handler/LobbyLobbyDataMsgHandler.cs
> attempte to fix NPE in LobbyLobbyDataMsgHandler

- Arrowgene.Ddon.Database/Files/Database/Script/schema_sqlite.sql
- Arrowgene.Ddon.Database/IDatabase.cs
- Arrowgene.Ddon.Database/Sql/Core/DdonSqlDbPawn.cs
- Arrowgene.Ddon.Database/Sql/Core/DdonSqlDbPawnTrainingStatus.cs
- Arrowgene.Ddon.GameServer/Characters/JobManager.cs
- Arrowgene.Ddon.GameServer/DdonGameServer.cs
- Arrowgene.Ddon.GameServer/GameStructure.cs
- Arrowgene.Ddon.GameServer/Handler/PawnTrainingGetPreparetionInfoToAdviceHandler.cs
- Arrowgene.Ddon.GameServer/Handler/PawnTrainingGetTrainingStatusHandler.cs
- Arrowgene.Ddon.GameServer/Handler/PawnTrainingSetTrainingStatusHandler.cs
- Arrowgene.Ddon.GameServer/Party/PawnPartyMember.cs
- Arrowgene.Ddon.LoginServer/Handler/CreateCharacterHandler.cs
- Arrowgene.Ddon.Shared/Entity/EntitySerializer.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/C2SPawnTrainingGetTrainingStatusReq.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/C2SPawnTrainingSetTrainingStatusReq.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CJobChangePawnJobRes.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CPawnTrainingGetTrainingStatusRes.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CPawnTrainingSetTrainingStatusRes.cs
- Arrowgene.Ddon.Shared/Entity/Structure/CDataPartyContextPawn.cs
- Arrowgene.Ddon.Shared/Entity/Structure/CDataPawnInfo.cs
- Arrowgene.Ddon.Shared/Entity/Structure/CDataPawnList.cs
- Arrowgene.Ddon.Shared/Entity/Structure/CDataPawnTrainingPreparationInfoToAdvice.cs
- Arrowgene.Ddon.Shared/Model/Pawn.cs
Allow training pawns, persisting in the database. All possible trainings are unlocked from the beginning with points enough to train again and again.
> Pawn training implementation

- Arrowgene.Ddon.GameServer/Characters/ItemManager.cs
Adds both stacks together, fixing the issue of one stack replacing the other when moving across storages
> Hotfix for adding stacks

- Arrowgene.Ddon.GameServer/Characters/ItemManager.cs
49594dc: Fix attempting to take items from a stack with not enough items
8969409: Fix infinite loop moving items to a stack that cant fit the amount being moved
> Hotfix moving stacks

- Arrowgene.Ddon.Cli/Command/Packet/PacketCommandOptions.cs
- Arrowgene.Ddon.Cli/Command/PacketCommand.cs
- Arrowgene.Ddon.Shared/Network/PacketId.cs
- Arrowgene.Ddon.Test/Cli/Command/PacketCommandTest.cs
Wrap the packet command options in a new class to manage complexity.
Add option to dump header bytes.
Add option to export packets as individual files using the input filename as new output folder.
Also fix c2l get game server list req which was falsely tagged as res.
> Update packet command

- Arrowgene.Ddon.Shared/Files/Assets/Shop.json
- Added support for shop npcs in the last 3 areas, Drawan, Zoma and Secret Proving Ground (Mergoda)
- Updated Colette Weapon Shop in WDT to sell items up to level 77 from 51.
- Updated Ferguson Armor Shop in WDT to sell items up to level 67 from 52.
> Update Shop.json for season 1 region.

- Arrowgene.Ddon.Shared/Files/Assets/Shop.json
- Added items to all shop npcs in Season 2 areas.
Areas List: Expedition Garrison, Protector's Retreat, Dana, Manun Village, Hollow of Beginnings: Gathering Area, Morfaul, Glyndwr, Tower of Ivanos.
> Update Shop.json for Season 2 region.

- Arrowgene.Ddon.Database/Files/Database/Script/schema_sqlite.sql
- Arrowgene.Ddon.Database/IDatabase.cs
- Arrowgene.Ddon.Database/Sql/Core/DdonSqlDbQuestReward.cs
- Arrowgene.Ddon.GameServer/Characters/RewardManager.cs
- Arrowgene.Ddon.GameServer/DdonGameServer.cs
- Arrowgene.Ddon.GameServer/Handler/QuestGetRewardBoxItemHandler.cs
- Arrowgene.Ddon.GameServer/Handler/QuestGetRewardBoxListHandler.cs
- Arrowgene.Ddon.GameServer/Handler/QuestQuestProgressHandler.cs
- Arrowgene.Ddon.GameServer/Quests/Quest.cs
- Arrowgene.Ddon.Shared/AssetReader/QuestAssetDeserializer.cs
- Arrowgene.Ddon.Shared/Entity/EntitySerializer.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/C2SQuestGetRewardBoxListReq.cs
- Arrowgene.Ddon.Shared/Model/Character.cs
- Arrowgene.Ddon.Shared/Model/Quest/QuestRewards.cs
- Save unclaimed rewards in the database.
- Limit up to 100 items stored per character.
- Add check for more than 4 random rewards for a quest in the asset
deserializer.
- Added a req packet for the box list handler and changed the parent
type.
> Save Rewards in the db

- Arrowgene.Ddon.Database/Files/Database/Script/schema_sqlite.sql
- Arrowgene.Ddon.Database/IDatabase.cs
- Arrowgene.Ddon.Database/Sql/Core/DdonSqlDbPawn.cs
- Arrowgene.Ddon.GameServer/Characters/JobManager.cs
- Arrowgene.Ddon.GameServer/GameStructure.cs
- Arrowgene.Ddon.GameServer/Handler/PawnSpSkillGetActiveSkillHandler.cs
- Arrowgene.Ddon.GameServer/Handler/PawnSpSkillSetActiveSkillHandler.cs
- Arrowgene.Ddon.GameServer/Party/PawnPartyMember.cs
- Arrowgene.Ddon.LoginServer/Handler/CreateCharacterHandler.cs
- Arrowgene.Ddon.Shared/Model/Pawn.cs
Fixes issue #327 
```sql
DROP TABLE IF EXISTS ddon_sp_skill;
CREATE TABLE IF NOT EXISTS ddon_sp_skill
(
"pawn_id"     INTEGER  NOT NULL,
"job"         SMALLINT NOT NULL,
"sp_skill_id" SMALLINT NOT NULL,
"sp_skill_lv" SMALLINT NOT NULL,
CONSTRAINT pk_ddon_sp_skill PRIMARY KEY (pawn_id, job, sp_skill_id),
CONSTRAINT fk_sp_skill_pawn_id FOREIGN KEY ("pawn_id") REFERENCES ddon_pawn ("pawn_id") ON DELETE CASCADE
);
```
> Allow having different pawn SP skills equipped per job

- Arrowgene.Ddon.GameServer/Quests/GenericQuest.cs
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20000001.json
Fixed an issue where the message id was not being assigned to the proper field in a delivery quest.
> fix: Fix issue with deliver quest NPC text

- Arrowgene.Ddon.Shared/Files/Assets/quests/q20000001.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20000002.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20000003.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20000007.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20000009.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20000014.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20000015.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20000017.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20000018.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20010000.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20010001.json
- Fix message_id so npcs display the correct dialog for their respective quests.
- Fix for q20000003_00: An Assistant's Assistant - Mayleaf is not part of that quest, it is Nancy instead, the waitress at the Tavern.
> Fix message id wq

- Arrowgene.Ddon.GameServer/Handler/QuestGetQuestCompletedListHandler.cs
- Arrowgene.Ddon.GameServer/Quests/GenericQuest.cs
- Arrowgene.Ddon.Shared/Entity/EntitySerializer.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/C2SQuestGetQuestCompleteListReq.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CQuestGetQuestCompleteListRes.cs
- Arrowgene.Ddon.Shared/Model/Quest/QuestType.cs
Added support for updating the list of completed quests after the player enters the game. This should resolve issues where players need to log out and back in after progressing far enough to unlock various features in the game.
Since the quest type enum values changed again, we need to update the quest type field in the DB.
Update the quest type field from `0` to `3` in the tables `ddon_completed_quests` and `ddon_quest_progress`
> Implement query for completed quest IDs

- Arrowgene.Ddon.Shared/Files/Assets/quests/q20000000.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20000004.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20000005.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20000006.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20000008.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20000010.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20000012.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20000013.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20000016.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20005004.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20005011.json
Authored by Dixdros
Hidell Plains
Lvl 7 - Request for Medicine - 薬を求めて
Lvl 8 - The Woes of A Merchant - ある行商人の悩み
Lvl 8 - An Assistant’s Assistant - 助手の助手
Lvl 8 - Crackdown on Store Vandals - 倉庫荒らしを懲らしめろ
Lvl 8 - A Heart Throbs Once More - ときめきをもう一度
Lvl 8 - Fabio’s Collectibles - ファビオの収集品
Lvl 8 - Confrontation with Scouts - Confrontation with the Scouts in the Dark
Lvl 9 - Fabio and Monster-Slaying - ファビオと魔物退治
Lvl 9 - A Transporter’s Tragedy - 輸送係の悲劇
Lvl 10 - Knight and Arisen - 騎士と覚者
Lvl 11 - The Traveller’s Scout - 旅人の露払い
Lvl 11 - Ambush In The Well’s Depths - 井戸底の伏兵達
Lvl 11 - The Raiding Orc Platoon -侵入のオーク小隊
Lvl 12 - The Knights’ Bitter Enemy - 騎士団の仇敵
Lvl 13 - A Petition to Rid of Demons in Ruins - 嘆願書対応　廃墟魔物退治
Lvl 13 - Whispers of the Dark - 闇からのささやき
Lvl 14 - Sky-Concealing Wings - …
> Added Hidell Plains world quests

- Arrowgene.Ddon.GameServer/Quests/GenericQuest.cs
- Arrowgene.Ddon.Shared/AssetReader/QuestAssetDeserializer.cs
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20000001.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20000002.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20000008.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20010000.json
- Arrowgene.Ddon.Shared/Model/Quest/QuestBlockType.cs
- Arrowgene.Ddon.Shared/Model/Quest/QuestNpcOrder.cs
- Added a new quest block type called "NewNpcTalkAndOrder" which allows the quest marker to show on NPCs that are spawned by quest flags.
- Fixed an issue with the quest "Beach Bandits" where the marker was showing up in the wrong location.
- Fixed an issue with the quest "A Transporter's Tragedy" where shiny items were no longer collectable.
- Adjusted existing quests "The Woes of A Merchant", "A Transporter's Tragedy", "Beach Bandits" and "The Raiding Orc Platoon" to use new order and talk commands.
> Adjust some World Quests

- Arrowgene.Ddon.GameServer/Quests/GenericQuest.cs
- Arrowgene.Ddon.GameServer/Quests/Quest.cs
- Arrowgene.Ddon.Shared/AssetReader/QuestAssetDeserializer.cs
- Arrowgene.Ddon.Shared/Files/Assets/quests/q00000020.json
- Arrowgene.Ddon.Shared/Model/InstancedEnemy.cs
- Arrowgene.Ddon.Shared/Model/Quest/QuestEnemyGroup.cs
- Arrowgene.Ddon.Shared/Model/Quest/QuestEnemyPlacementType.cs
Added ability to specify automatic or manual placement of enemies.
- Automatic placement just uses the enemies position in the array + the starting_index value (if provided).
- This is the default strategy if not provided. 
- Manual placement requires that every enemy as an additional "index" field, specifying the position in the group.
> Quest Enemy Placement

- Arrowgene.Ddon.GameServer/Handler/InstanceEnemyKillHandler.cs
- Arrowgene.Ddon.GameServer/Party/PartyQuestState.cs
- Arrowgene.Ddon.GameServer/Quests/GenericQuest.cs
- Arrowgene.Ddon.Shared/AssetReader/QuestAssetDeserializer.cs
- Arrowgene.Ddon.Shared/Entity/EntitySerializer.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CInstanceEnemyDieNtc.cs
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20000000.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20005010.json
- Arrowgene.Ddon.Shared/Model/InstancedEnemy.cs
- Fixed an issue where the quest enemies were being indicated as active before the step in the quest was reached.
- Add ability to mark an enemy in a group as required or not.
> Quest Enemy Spawn Adjustments

- Arrowgene.Ddon.GameServer/Characters/StageManager.cs
- Arrowgene.Ddon.GameServer/Handler/LobbyLobbyDataMsgHandler.cs
- Arrowgene.Ddon.GameServer/Handler/StageAreaChangeHandler.cs
- Added more safe areas where reset NTC is sent.
- S2C_INSTANCE_AREA_RESET_NTC gets sent every time you zone in a safe area, meaning, when inside The White Dragon Temple, it'll happen a lot more, i don't know if this is a problem, if it is, i can remove the areas inside The White Dragon Temple until resolved.
> Added more safe areas to StageAreaChangeHandler.cs

- Arrowgene.Ddon.Shared/Files/Assets/quests/q20000000.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20000004.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20000005.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20000006.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20000008.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20000010.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20000012.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20000013.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20000016.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20005004.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20005011.json
- Fixes for some of the World Quests that was introduced last week.
- Based on videos and 2 wikis.
- Changed exp values for enemies based on DDOn-Tools values.
> Fixes for some World Quests

- Arrowgene.Ddon.Shared/Files/Assets/quests/q00000001.json
If a player logs out or disconnects during the first MSQ, when they log back in, they will be warped back to the tutorial stage.
> Add rule to warp player during first MSQ

- Arrowgene.Ddon.Cli/Arrowgene.Ddon.Cli.csproj
- Arrowgene.Ddon.Client/Arrowgene.Ddon.Client.csproj
- Arrowgene.Ddon.Database/Arrowgene.Ddon.Database.csproj
- Arrowgene.Ddon.GameServer/Arrowgene.Ddon.GameServer.csproj
- Arrowgene.Ddon.LoginServer/Arrowgene.Ddon.LoginServer.csproj
- Arrowgene.Ddon.Rpc.Web/Arrowgene.Ddon.Rpc.Web.csproj
- Arrowgene.Ddon.Rpc/Arrowgene.Ddon.Rpc.csproj
- Arrowgene.Ddon.Server/Arrowgene.Ddon.Server.csproj
- Arrowgene.Ddon.Shared/Arrowgene.Ddon.Shared.csproj
- Arrowgene.Ddon.Shared/Crypto/BlowFish.cs
- Arrowgene.Ddon.Shared/Crypto/Camellia.cs
- Arrowgene.Ddon.Test/Arrowgene.Ddon.Test.csproj
- Arrowgene.Ddon.WebServer/Arrowgene.Ddon.WebServer.csproj
Enabled the build flag which detects underflow and overflow by default. Marked certain functions as unchecked in the networking library as they are depending on this behavior for certain operations.
> Add underflow and overflow detection

- Arrowgene.Ddon.GameServer/BazaarManager.cs
- Arrowgene.Ddon.GameServer/Handler/BazaarGetItemPriceLimitHandler.cs
Addresses issue #357.
Tweaks the tax algorithm to match the UI; there should be no tax on sales of **up to** 20 GP, because tax is floored before its subtracted from the total sale price. The minimum/maximum price and max stack are also set to what was apparently on the live server, although those min/max prices were also seemingly item dependent.
Old:
> Min = 0, Max = ushort.MaxValue, Stack = 99
New:
> Min = 1, Max = 99,999, Stack = 10
> Fix: You cant receive bazaar proceeds when the total sum is 0 

- Arrowgene.Ddon.Cli/Command/DbMigrationCommand.cs
- Arrowgene.Ddon.Cli/Program.cs
- Arrowgene.Ddon.Database/DdonDatabaseBuilder.cs
- Arrowgene.Ddon.Database/Files/Database/Script/migration_mail_sqlite.sql
- Arrowgene.Ddon.Database/Files/Database/Script/schema_sqlite.sql
- Arrowgene.Ddon.Database/IDatabase.cs
- Arrowgene.Ddon.Database/Sql/Core/DdonSqlDb.cs
- Arrowgene.Ddon.Database/Sql/Core/DdonSqlDbMeta.cs
- Arrowgene.Ddon.Database/Sql/Core/DdonSqlDbUnlockedSecretAbility.cs
- Arrowgene.Ddon.Database/Sql/Core/Migration/DatabaseMigrator.cs
- Arrowgene.Ddon.Database/Sql/Core/Migration/IMigrationStrategy.cs
- Arrowgene.Ddon.Database/Sql/Core/Migration/MailMigration.cs
- Arrowgene.Ddon.Database/Sql/DdonMariaDb.cs
- Arrowgene.Ddon.Database/Sql/DdonPostgresDb.cs
- Arrowgene.Ddon.Database/Sql/DdonSqLiteDb.cs
- Arrowgene.Ddon.Shared/Entity/DatabaseMeta.cs
- Arrowgene.Ddon.Test/Database/DatabaseMigratorTest.cs
Addresses #93 and #102 
Implement a simple database migrator CLI command that will read the current database version and figure out which strategies to run to upgrade to the target database version.
The migrator will have a list of IMigrationStrategy objects, each with a From and To properties and a Migrate method. The migrator will figure out the shortest path to upgrade from one version to another.
For example, if the database is in version 1 and the target version is 4, it'll try running the least number of migrations to reach version 4:
If there's strategies to migrate from version 1 to 2, 2 to 3, 3 to 4, but also, there's a strategy to migrate from 1 to 4 directly, it'll favour the later.
These strategies are regular C# code, meaning you can call SQL but also perform complex logic if …
> Database migrator proposal

- Arrowgene.Ddon.GameServer/Characters/JobManager.cs
- Arrowgene.Ddon.Shared/Entity/EntitySerializer.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CSkillNormalSkillLearnNtc.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CSkillPawnNormalSkillLearnNtc.cs
- Arrowgene.Ddon.Shared/Network/PacketId.cs
Alert all party members with an NTC when a player or pawn ranks up a custom skill.
Addresses issue #359.
New to C# so the pallet search is probably wonky.
> Fix: Skills don't do damage after leveling it up 

- Arrowgene.Ddon.GameServer/Handler/InstanceEnemyKillHandler.cs
Fixed issue where check was checking the wrong value which resulted in pawns not receiving exp.
> bugfix: Fix issue with pawn exp

- Arrowgene.Ddon.Database/Files/Database/Script/schema_sqlite.sql
UNIQUE vs PRIMARY key constraint for ddon_storage_item.
> Make schema match migration

- Arrowgene.Ddon.Shared/Csv/ClientItemInfoCsv.cs
- Arrowgene.Ddon.Shared/Files/Assets/itemlist.csv
- Arrowgene.Ddon.Shared/Model/ItemSubCategory.cs
Address misordered Name and Subcategory in ClientItemInfoCsv, fix ItemSubCategory enum, fix bad ranks from incorrect hex pattern for high rank items in itemlist.csv.
> Hotfix: ClientItemInfo and itemlist.csv errors

- Arrowgene.Ddon.LoginServer/Handler/ClientLoginHandler.cs
When on login, the server finds an existing connection in the ddon_connection table of the DB, it'll check if there's a client for that account already in the server.
If there isn't, the ddon_connection entry will be deleted, allowing the user to log in.
> Remove stale connections

- Arrowgene.Ddon.GameServer/Characters/EquipManager.cs
Fixed an issue which causes the player to timeout when they equip items from the expanded storage.
> fix: Fix issue with equipping items

- Arrowgene.Ddon.GameServer/Characters/ExpManager.cs
Changed the way the text pops up for bonus exp to reflect how it was in the original game.
> Fix EXP bonus popup text

- Arrowgene.Ddon.Database/Files/Database/Script/migration_stamp_sqlite.sql
- Arrowgene.Ddon.Database/Files/Database/Script/schema_sqlite.sql
- Arrowgene.Ddon.Database/Sql/Core/DdonSqlDbStampBonus.cs
Had the schema wrong and fixed the migration to match the schema rather than the other way around.
Many apologies.
Restores the migration to what was originally presented, and then updates the *schema* to properly match that.
> Hotfix: Stamps, again.

- Arrowgene.Ddon.GameServer/Characters/ItemManager.cs
- Arrowgene.Ddon.GameServer/Handler/CraftStartCraftHandler.cs
- Arrowgene.Ddon.GameServer/Handler/CraftStartEquipColorChangeHandler.cs
- Arrowgene.Ddon.GameServer/Handler/CraftStartEquipGradeUpHandler.cs
- Arrowgene.Ddon.GameServer/Handler/CraftStartQualityUpHandler.cs
Crests were not persisting if your gear would change quality/enhance/dye, now they do.
This also tweaks Quality RNG behaviour to be more accurate to Live.
> Fix: Crests will now persist through Gear upgrades

- Arrowgene.Ddon.Cli/Command/ServerCommand.cs
- Arrowgene.Ddon.Cli/Program.cs
- Arrowgene.Ddon.Cli/Setting.cs
- Arrowgene.Ddon.GameServer/Handler/ClientChallengeHandler.cs
- Arrowgene.Ddon.GameServer/Handler/ConnectionReserveServerHandler.cs
- Arrowgene.Ddon.Shared/Entity/EntitySerializer.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/C2SConnectionReserveServerReq.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CConnectionReserveServerRes.cs
This PR adds support for the following:
- Specifying the log directory path in the config file
- Specifying the config file path with command line arguments
- Adding DB entries for connections in different servers when the client requests it
These three features combined allow running multiple instances of the server, sharing assets and database, with the client being able to switch between them using the ingame World Select option by doing the following:
1. Create a copy of the config file (Files/Arrowgene.Ddon.config.json), naming it, for example, Arrowgene.DDon.config-2.json
2. Editing the config file to have a different LogPath directory, for example, "Logs-2"
3. Editing the ports 52000, 52099 and 52100 to different values, for example, 42000, 42099 and 42100
4. Editing the …
> Support for different servers acting as channels

- Arrowgene.Ddon.Database/Files/Database/Script/schema_sqlite.sql
- Arrowgene.Ddon.GameServer/Characters/CraftManager.cs
- Arrowgene.Ddon.GameServer/GameServerSetting.cs
- Arrowgene.Ddon.GameServer/Handler/CraftGetCraftProductInfoHandler.cs
- Arrowgene.Ddon.GameServer/Handler/CraftStartAttachElementHandler.cs
- Arrowgene.Ddon.GameServer/Handler/CraftStartCraftHandler.cs
- Arrowgene.Ddon.GameServer/Handler/CraftStartEquipColorChangeHandler.cs
- Arrowgene.Ddon.GameServer/Handler/CraftStartEquipGradeUpHandler.cs
- Arrowgene.Ddon.GameServer/Handler/CraftStartQualityUpHandler.cs
- Arrowgene.Ddon.Server/GameLogicSetting.cs
- Arrowgene.Ddon.Server/ServerSetting.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CCraftCraftRankUpNtc.cs
- Arrowgene.Ddon.Shared/Network/PacketId.cs
- Arrowgene.Ddon.Test/GameServer/Characters/CraftManagerTest.cs
Fixes
- No exp from crests.
- Recipes with inherent multiple items being crafted only returning no. of queued creations instead of no. of queued creations times inherent no.
- Promotion pop up wrongly shown after promotion.
- Menu getting stuck at item retrieval after rank max has been reached.
- Cascade on delete missing for new databases.
- Pawn craft skill & exp-related columns missing for new databases.
Enhancements:
- Move craft skill configs to a new settings section
Open points:
- C2S_PAWN_DELETE_MYPAWN_REQ missing implementation 
- Migration for cascade on delete for existing DBs
> Fix various crafting exp, rank & promotion-related bugs.

- Arrowgene.Ddon.Shared/Files/Assets/CraftingRecipes.json
A simple validation by checking the combination of recipeId + itemId revealed the duplicate item ids.
> Remove recipes which create items that are already present in category 26.

- Arrowgene.Ddon.GameServer/Handler/SkillSetOffAbilityHandler.cs
Fixes a minor bug where removing an augment at Archibald would actually remove that augment and the one after it. The augment UI wouldn't reflect that fact (because it lies as easily as it breathes), but the character status UI would show the true augment loadout.
> Fix: Augment removal bug

- Arrowgene.Ddon.GameServer/Characters/ItemManager.cs
Fixes an issue with the item handling when adding to a large stack of items. Because of deferred updating of stack counts, combined with the rollover logic to handle excess amounts, you'd get weird cases where 950 + 50 = 951, rather than 999 in one stack and 1 in another. The missing amount would be permanently lost, which is annoying even if you probably won't miss it if you have 999 of any one item.
Now when you're done "filling" a stack, you should revert to the "no target slot" behavior and dump into the next valid slot/stack.
> Fix: Storage stacking bug

- Arrowgene.Ddon.GameServer/Handler/CharacterGetReviveChargeableTimeHandler.cs
Resolves #190
Changes the revival timer from a set 24 hour duration to always refreshing at 12:00 AM JST.
> Setting revival timer to 12:00 AM JST to align with original server.

- Arrowgene.Ddon.GameServer/Handler/CharacterChargeRevivePointHandler.cs
- Arrowgene.Ddon.GameServer/Handler/CharacterGetReviveChargeableTimeHandler.cs
Rewrote code to factor in JST in both `CharacterChargeRevivePointHandler` and `LastRevivalPowerRechargeTime` to solve #190 again.
Thanks for all your assistance and patience, Laith and co!
**Joined server after server start, with full revives:**
No revival option, as full revives are present.
**Expended revives:**
Given revival option, and told 'You have refreshed today already' on second attempt with NPC.
**Expended revives again:**
'You have refreshed today already'.
**Shifted server time to next day, no server restart, character relog, full revives:**
No revival option, as full revives are present, as expected.
**Expended revives:**
Given revival option, and told 'You have refreshed today already' on second attempt with NPC.
> Amended and Rewritten Revive Timer (12:00AM JST)

- Arrowgene.Ddon.Cli/Command/ClientCommand.cs
- Arrowgene.Ddon.Client/ArcArchive.cs
- Arrowgene.Ddon.Shared/Csv/GmdCsv.cs
- Arrowgene.Ddon.Shared/Util.cs
To allow patching on linux, the gmd.csv has to have the paths to the arc files using forward slashes, which work both on windows and linux.
However, after naively replacing all slashes to forward slahes in the csv, since arc files internally have their archived file paths using backward slashes, when comparing fields using a simple string comparison, the patcher couldn't find the files contained in the arc.
To work around this, paths read from the csv are normalized into using backward slashes.
> Escape gmd.csv path fields

- Arrowgene.Ddon.GameServer/Handler/InstanceEnemyKillHandler.cs
Before, if you werent the context leader and your roll had 0 items, youd still see the bag but get no items And if your roll had items but the leader didnt, you wouldnt see the bag, therefore be unable to get your items
This PR fixes it
> Fix showing the item bag on enemy kill

- Arrowgene.Ddon.GameServer/Handler/ConnectionPingHandler.cs
- Arrowgene.Ddon.LoginServer/Handler/ClientPingHandler.cs
- Arrowgene.Ddon.Server/DdonServer.cs
- Arrowgene.Ddon.Server/Network/Consumer.cs
- Arrowgene.Ddon.Server/Network/IPacketHandler.cs
- Arrowgene.Ddon.Server/Network/PacketHandler.cs
- Arrowgene.Ddon.Server/Network/PingRequestPacketHandler.cs
- Arrowgene.Ddon.Server/Network/StructurePacketHandler.cs
- Arrowgene.Ddon.Shared/Entity/EntitySerializer.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/C2LPingReq.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/C2SConnectionPingReq.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/L2CPingRes.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CConnectionPingRes.cs
To prevent half-connected sockets, both the login and game server's ping handlers now use a timer to periodically check if the last ping has been too long ago. If it has been, the server will try sending a packet to the client, if the packet goes through, the client is still alive and no further action is needed;
if the packet doesn't go through, the client is dead, the write will fail, and it'll be cleaned up.
This will (hopefully) solve the S-6008 error, where the server thinks the user is still connected to the server and therefore prevents new connections from them
> Periodically check age of client pings

- Arrowgene.Ddon.GameServer/Characters/GpCourseManager.cs
- Arrowgene.Ddon.GameServer/Characters/PlayPointManager.cs
- Arrowgene.Ddon.GameServer/DdonGameServer.cs
- Arrowgene.Ddon.GameServer/Handler/InstanceEnemyKillHandler.cs
- Arrowgene.Ddon.GameServer/Handler/JobJobValueShopBuyItemHandler.cs
- Arrowgene.Ddon.GameServer/Party/PartyQuestState.cs
- Arrowgene.Ddon.Shared/Files/Assets/GpCourseInfo.json
- Added support for PP bonus for GP Course
- Added a sample course definition for EXP and PP
- Fixed an issue at the PP NPC where price was incorrectly calculated
- Fixed an issue where the incorrect calculation causing an overflow exception.
> Add Support for GP Course PP bonus

- Arrowgene.Ddon.GameServer/Characters/ExpManager.cs
- Arrowgene.Ddon.GameServer/Characters/GpCourseManager.cs
- Arrowgene.Ddon.GameServer/Handler/InstanceEnemyKillHandler.cs
- Arrowgene.Ddon.Server/GameLogicSetting.cs
- Added a check based on the level distribution of party members as described in the DDON wiki.
- Added a check based on the maximum level of the target enemy when compared to the maximum level of a party member.
- Added options to enable/disable both features.
- Added options to configure the level ranges and EXP rate rewarded for both options.
- Added support for course effect which temporarily disables these
checks.
> Add checks around EXP rewards

- Arrowgene.Ddon.GameServer/Characters/GpCourseManager.cs
- Arrowgene.Ddon.GameServer/Handler/InstanceEnemyKillHandler.cs
Added support for detecting the Blood Orb GP course bonus and applying the bonus value when killing enemies.
> feat: Add support for GP course Blood Orb bonus

- Arrowgene.Ddon.GameServer/Characters/OrbUnlockManager.cs
Fixed an issue where the strength node in the Pawn BO tree was using incorrect BO cost value when performing checks and subtracting from the players wallet.
> fix: Fix Pawn BO tree cost

- Arrowgene.Ddon.Database/Sql/Core/DdonSqlDbCharacterCommon.cs
- Arrowgene.Ddon.GameServer/Characters/CharacterManager.cs
- Arrowgene.Ddon.GameServer/Characters/HubManager.cs
- Arrowgene.Ddon.GameServer/Handler/CharacterSwitchGameModeHandler.cs
Attempt to fix an issue where the player sometimes is "dead" when they log in, join parties or switch to some hub area. It seems that the HP is being saved as 0 sometimes in the DB. So when the context gets updated the player is dead, unable to select any menu options.
> fix: Fix some oddities with character

- Arrowgene.Ddon.GameServer/Characters/HubManager.cs
- Arrowgene.Ddon.GameServer/Handler/BattleContentContentResetHandler.cs
- Arrowgene.Ddon.GameServer/Handler/InstanceGetGatheringItemHandler.cs
- Fixed an issue where gear equipped from the box was not reflected visually in other party member clients.
- Fixed an issue where when the player reset their progress, their level and gear was not reflected properly to other players.
> fix: Fix issue with equip in BBM

- Arrowgene.Ddon.GameServer/Characters/ExpManager.cs
- Arrowgene.Ddon.GameServer/Handler/InstanceEnemyKillHandler.cs
- Arrowgene.Ddon.Server/GameLogicSetting.cs
When a pawn is outside the valid party level range and the player is a higher level than the pawn, the pawn will gain exp at a boosted rate to help get it back closer to the players level range.
> feat: Implement pawn catchup system

- Arrowgene.Ddon.GameServer/Characters/ExpManager.cs
Fixed an issue where the pawn ID got dropped from the EXP NTC which causes the pawn EXP gain to not show in the log.
> fix: Fix issue with pawn exp notification

- Arrowgene.Ddon.GameServer/Characters/ItemManager.cs
- Arrowgene.Ddon.GameServer/DdonGameServer.cs
- Arrowgene.Ddon.GameServer/Handler/BattleContentContentResetHandler.cs
- Arrowgene.Ddon.GameServer/Handler/CharacterCharacterPenaltyReviveHandler.cs
- Arrowgene.Ddon.Shared/Model/Storages.cs
Implemented a mechanic for BBM where if the player chooses to homepoint after dying inside the maze, any item which is not currently equipped to the character will be lost.
> feat: Items not equipped are lost in BBM on homepoint

- Arrowgene.Ddon.GameServer/Handler/PawnGetRegisteredPawnDataHandler.cs
- Arrowgene.Ddon.Shared/Entity/Structure/CDataPawnInfo.cs
- Arrowgene.Ddon.Shared/Model/Pawn.cs
Fixed an issue where the pawn skills were not visible when looking at the skills before hiring.
> fix: Fix issue where pawn skills can't be previewed

- Arrowgene.Ddon.GameServer/Enemies/InstanceEnemyManager.cs
- Arrowgene.Ddon.GameServer/Handler/InstanceEnemyKillHandler.cs
- Arrowgene.Ddon.GameServer/Handler/InstanceGetEnemySetListHandler.cs
- Arrowgene.Ddon.GameServer/Handler/InstanceTraningRoomSetEnemyHandler.cs
- Arrowgene.Ddon.GameServer/Party/PartyQuestState.cs
- Arrowgene.Ddon.GameServer/Quests/Quest.cs
Fixed an exception which occurs the client requests enemies for a subgroup even when there are monsters are already populated in that node.
> fix: Fix exception related to subgroups

- Arrowgene.Ddon.GameServer/Characters/GpCourseManager.cs
- Arrowgene.Ddon.GameServer/Handler/CharacterGetReviveChargeableTimeHandler.cs
- Arrowgene.Ddon.LoginServer/Handler/GetCharacterListHandler.cs
- Arrowgene.Ddon.Shared/Files/Assets/GpCourseInfo.json
- Added support for unlimited revives in the course manager.
- Renamed "Arrowgene QOL Course" to "Arrowgene Blessing".
- Added unlimited revive effect to "Arrowgene Blessing".
- Fixed issue where ended course still shows up.
- Added support for upcoming course effect to report "activating".
> feat: Enable "Unlimited revive refills" course effect

- Arrowgene.Ddon.GameServer/Handler/InstanceEnemyKillHandler.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/C2SInstanceEnemyKillReq.cs
Add a check for the "IsNoBattleReward" in the enemy kill handler.
> fix: Fix issue where death rewards items when running away

- Arrowgene.Ddon.GameServer/Handler/QuestGetSetQuestListHandler.cs
- Arrowgene.Ddon.GameServer/Party/PartyGroup.cs
- Arrowgene.Ddon.GameServer/Party/PartyQuestState.cs
- Fixed an issue where world quests completion was not being tracked properly.
- Fixed an issue where the area quest fetch was not cleaning up state properly.
- Added some defensive checks to prevent exceptions from being thrown.
> fix: Fix issue with spontaneous world quests

- Arrowgene.Ddon.Shared/Files/Assets/SpecialShops.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q50206000.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q50300010.json
- Fixed an issue with the crimson HS weapon having the wrong price.
- Adjusted the Zuhl nameplate in EXM.
- Adjusted the check for the spirit dragon adds.
> Fix nameplate exm war

- Arrowgene.Ddon.GameServer/Characters/BoardManager.cs
- Arrowgene.Ddon.GameServer/Handler/EntryBoardEntryBoardItemEntryHandler.cs
- Arrowgene.Ddon.GameServer/Handler/EntryBoardEntryBoardItemLeaveHandler.cs
- Fixed an issue where the party wasn't able to ready up when all slots were filled.
- Fixed an issue where if a member quit after some players pressed ready, that they would be stuck until the timer expired.
> fix: Fix issues with EXM recruitment board

- Arrowgene.Ddon.GameServer/Characters/BoardManager.cs
- Arrowgene.Ddon.GameServer/Characters/QuestManager.cs
- Arrowgene.Ddon.GameServer/DdonGameServer.cs
- Arrowgene.Ddon.GameServer/Handler/CharacterCharacterDownHandler.cs
- Arrowgene.Ddon.GameServer/Handler/EntryBoardEntryBoardItemCreateHandler.cs
- Arrowgene.Ddon.GameServer/Handler/EntryBoardEntryBoardItemReadyHandler.cs
- Arrowgene.Ddon.GameServer/Handler/EntryBoardPartyRecruitCategoryListHandler.cs
- Arrowgene.Ddon.GameServer/Handler/PartyPartyChangeLeaderHandler.cs
- Arrowgene.Ddon.GameServer/Handler/PartyPartyJoinHandler.cs
- Arrowgene.Ddon.GameServer/Handler/PartyPartyLeaveHandler.cs
- Arrowgene.Ddon.GameServer/Handler/QuestGetEndContentsRecruitListHandler.cs
- Arrowgene.Ddon.GameServer/Handler/QuestPlayStartTimerHandler.cs
- Arrowgene.Ddon.GameServer/Handler/StageAreaChangeHandler.cs
- Arrowgene.Ddon.GameServer/Handler/WarpGetReturnLocationHandler.cs
- Arrowgene.Ddon.GameServer/Party/PartyGroup.cs
- Arrowgene.Ddon.GameServer/Quests/GenericQuest.cs
- Arrowgene.Ddon.GameServer/Quests/Quest.cs
- Arrowgene.Ddon.Rpc/Command/InfoCommand.cs
- Arrowgene.Ddon.Shared/Asset/RecruitmentBoardCategoryAsset.cs
- Arrowgene.Ddon.Shared/AssetReader/QuestAssetDeserializer.cs
- Arrowgene.Ddon.Shared/AssetReader/RecruitmentBoardCategoryDeserializer.cs
- Arrowgene.Ddon.Shared/AssetRepository.cs
- Arrowgene.Ddon.Shared/Entity/EntitySerializer.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/C2SEntryBoardPartyRecruitCategoryListReq.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CEntryBoardPartyRecruitCategoryListRes.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2C_63_0_16_NTC.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2C_SEASON_62_38_16_NTC.cs
- Arrowgene.Ddon.Shared/Entity/Structure/CDataEntryRecruitCategoryData.cs
- Arrowgene.Ddon.Shared/Files/Assets/RecruitmentGroups.json
- Arrowgene.Ddon.Shared/Network/PacketId.cs
- Fixed an issue where contexts were not properly cleared after resetting the instance.
- Fixed an issue where a NPE is hit in the RPC info command when players are logging in.
- Attempt to address an issue about what happens to a player when they die during an EXM.
- Enabled non-exm recruitment from the recruitment board.
- Send some unknown packets found during EXM exploration but unsure what they do.
- Fixed some packets which were named as S2C but were actually C2S.
- Fixed parsing for adding end contents purpose.
- Fixed unexpected party invite expiration.
> fix: Fix small bugs

- Arrowgene.Ddon.Shared/Files/Assets/quests/q50101020.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q50102020.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q50103020.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q50104000.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q50201000.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q50202000.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q50202003.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q50203000.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q50204002.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q50206000.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q50300001.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q50300003.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q50300006.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q50300010.json
- Adjusted EXM such that they drop EXP, BO and JP.
- Adjusted EM5 to make it closer to original EXM implementation and make rewards worthwhile.
- Block monsters in "Phindym War Chronicles" that should not be spawning.
> adjustments: Enhance rewards for EXM

- Arrowgene.Ddon.GameServer/Handler/QuestGetEndContentsGroupHandler.cs
- Arrowgene.Ddon.GameServer/Quests/Quest.cs
- Arrowgene.Ddon.Shared/AssetReader/QuestAssetDeserializer.cs
- Arrowgene.Ddon.Shared/Files/Assets/quests/q50204001.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q50206000.json
- Arrowgene.Ddon.Shared/Model/Quest/QuestMissionParams.cs
- Implemented the EXM "Onset of Darkness: Restricted Stage" 
- Add support for selectable rewards in EXM
- Added think table type to ghost in q50206000.json
- Added option to provide a start position in the mission params
- Sort EXM quests by quest ID instead of dictionary order
> feat: Implement the EXM "Onset of Darkness: Restricted Stage"

- Arrowgene.Ddon.Database/Files/Database/Script/migration_msq_2.0.sql
- Arrowgene.Ddon.Database/Files/Database/Script/migration_msq_2.1.sql
- Arrowgene.Ddon.Database/Files/Database/Script/migration_msq_2.2.sql
- Arrowgene.Ddon.Database/Files/Database/Script/migration_msq_2.3.sql
Fixed an issue where the MSQ migrations through a constraint failure exception when no characters in the database match the query.
> fix: Fix issue with 2.x migration

- Arrowgene.Ddon.Shared/Files/Assets/SpecialShops.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20035006.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20075007.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20080006.json
- Fix q20035006 by adjusting the group ID from 20 -> 2
- Fix q20075007 by correcting enemy IDs to be valid hex numbers
- Fix q20080006 by adjusting the spawn location to Water Channel Ruins, group 1.
- Fix crimson exchange where the wrong Crimson Firangi was being rewarded for HS.
> fix: Fix small bugs found in various quests and rewards

- Arrowgene.Ddon.GameServer/Quests/GenericQuest.cs
Fixed an issue where the server consumed items for delivery quests and then caused an exception which makes the player disconnect.
> fix: Fixed an issue with new deliver command

- Arrowgene.Ddon.GameServer/Handler/InstanceGetEnemySetListHandler.cs
- Arrowgene.Ddon.GameServer/Party/PartyQuestState.cs
- Arrowgene.Ddon.GameServer/Quests/Quest.cs
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20010001.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20015005.json
Allow world monsters to consume a group until the quest reaches a step which requires the group.
> refactor: rework quest enemy spawn

- Arrowgene.Ddon.GameServer/Characters/QuestManager.cs
- Arrowgene.Ddon.GameServer/Characters/StageManager.cs
- Arrowgene.Ddon.GameServer/Context/ContextManager.cs
- Arrowgene.Ddon.GameServer/GatheringItems/InstanceEventDropItemManager.cs
- Arrowgene.Ddon.GameServer/Handler/InstanceGetEnemySetListHandler.cs
- Arrowgene.Ddon.GameServer/Handler/PartyPartyCreateHandler.cs
- Arrowgene.Ddon.GameServer/Handler/QuestGetCycleContentsStateListHandler.cs
- Arrowgene.Ddon.GameServer/Handler/QuestGetTutorialQuestListHandler.cs
- Arrowgene.Ddon.GameServer/Party/PartyQuestState.cs
- Arrowgene.Ddon.GameServer/Quests/Quest.cs
- Arrowgene.Ddon.Shared/Files/Assets/quests/q00020010.json
- docs/quests/holiday_personal_quests.md
- Don't populate quest information for quests which are not enabled.
- Add a new function to check if a quest is enabled which can handle null without causing an exception.
-  Mark Bonus Lobby as a safe area
- Add potential fix for BGM which don't end
- Reverted the "improved" quest groups as it doesn't work 100% of the time
> fix: Various fixes related to quests

- Arrowgene.Ddon.GameServer/GatheringItems/InstanceEventDropItemManager.cs
- Arrowgene.Ddon.Shared/Asset/EventDropsAsset.cs
- Arrowgene.Ddon.Shared/AssetReader/EventDropAssetDeserializer.cs
- Arrowgene.Ddon.Shared/Files/Assets/EventDrops.json
- Arrowgene.Ddon.Shared/Files/Assets/SpecialShops.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20070005.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q60301001.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q60301054.json
- Arrowgene.Ddon.Shared/Model/EventItemConstraint.cs
- Fixed enemy placement in q20070005.
- Fixed issue where seasonal event for Halloween completes incorrectly.
- Added missing gacha costumes to special shop NPC.
- Updated event item constraint system to take optional arguments.
- Updated event item constraint system to specify if all items are required or 1 item.
- Fixed bug in required item check.
Co-authored-by: Dogs
> fixes: Fix issue with quests

- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CQuestJoinLobbyQuestInfoNtc.cs
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20100001.json
- Fix issue with q20100001 by removing unused enemy node.
Authored-by: Dogs
> fix: World Quests

- Arrowgene.Ddon.GameServer/Handler/CharacterSwitchGameModeHandler.cs
The index value was improperly assigned when generating a new character for BBM which causes certain skills to not work as intended.
> fix: Fix BBM learned normal skills

- Arrowgene.Ddon.GameServer/Party/PartyQuestState.cs
Fixed an issue introduced with the quest schedule ID where the quest progress for the next quest was set to the schedule id.
> fix: Fix bug with next quest progress

- Arrowgene.Ddon.GameServer/Party/PartyQuestState.cs
Fixed an issue where the next quest was not set to the next quest but instead the current quest.
> fix: Fix issue with next quest

- Arrowgene.Ddon.GameServer/Handler/QuestGetRewardBoxListHandler.cs
Fixed an issue where the quest reward handler will crash if a quest reward is available for a quest with no definition.
> fix: Fix issue with null quest

- Arrowgene.Ddon.GameServer/Characters/ExpManager.cs
- Arrowgene.Ddon.Server/GameLogicSetting.cs
Added a new GameSetting DisableExpCorrectionForMyPawn which disables party level difference checks if all members of the party are owned by the same character.
> feat: Add new exp penalty knob

- Arrowgene.Ddon.GameServer/Characters/QuestManager.cs
- Arrowgene.Ddon.GameServer/Handler/InstanceEnemyKillHandler.cs
- Arrowgene.Ddon.GameServer/Handler/InstanceGetEnemySetListHandler.cs
- Arrowgene.Ddon.GameServer/Handler/PartyPartyCreateHandler.cs
- Arrowgene.Ddon.GameServer/Quests/GenericQuest.cs
Fixed an issue where tutorial quests with enemies caused an exception because the wrong quest state mananager was queried.
> fix: Fix issue with tutorial quests

- Arrowgene.Ddon.GameServer/Handler/InstanceGetEnemySetListHandler.cs
- Arrowgene.Ddon.GameServer/Handler/QuestSetPriorityQuestHandler.cs
- Arrowgene.Ddon.GameServer/Quests/GenericQuest.cs
- Arrowgene.Ddon.GameServer/Quests/Quest.cs
- Arrowgene.Ddon.Shared/Asset/QuestAsset.cs
- Arrowgene.Ddon.Shared/AssetReader/QuestAssetDeserializer.cs
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20005001.json
- If an active quest is a main story quest or EXM, these quests will override all behavior of a spawn group for the duration of the quest.
- If any other type of quest is activated, the spawns will only be overridden if the current step of the quest requires the spawn group.
> fixes: Adjust enemy spawn behavior for quests

- Arrowgene.Ddon.GameServer/Chat/Command/Commands/PartyInviteCommand.cs
- Don't allow a player to be invited if they exist in a different game mode.
- Restrict party size to 4 if gamemode is Bitterblack Maze.
> fix: Restrictions on /invite

- Arrowgene.Ddon.Database/Arrowgene.Ddon.Database.csproj
- Arrowgene.Ddon.Database/DdonDatabaseBuilder.cs
postgress does not support the tinyint data type, so it gets replaced in the sql file with smallint
the Npgsql lib has an sql injection vuln so I also upgraded it to a version that has it patched
- [x ] The project compiles
- [x ] The PR targets `develop` branch
> fix for postgres

- Arrowgene.Ddon.GameServer/Handler/QuestGetCycleContentsStateListHandler.cs
- Arrowgene.Ddon.GameServer/Handler/StageUnisonAreaChangeBeginRecruitmentHandler.cs
- Arrowgene.Ddon.GameServer/Quests/GenericQuest.cs
- Arrowgene.Ddon.GameServer/Quests/Quest.cs
- Arrowgene.Ddon.Shared/AssetReader/QuestAssetDeserializer.cs
- Arrowgene.Ddon.Shared/Files/Assets/EventDrops.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20085004.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21014012.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21017014.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q60200022.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q60301055.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q60301056.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q60301057.json
- Arrowgene.Ddon.Shared/Model/Quest/QuestNpcOrder.cs
- docs/quests/holiday_personal_quests.md
Implements 2018 Christmas quests.
> event quest: Implement 2018 Christmas seasonal event quests

- Arrowgene.Ddon.Rpc.Web/Route/ServerStatusRoute.cs
This will allow DDOn Tools to query all other servers in the cluster without having to guess the RPC port or be made aware of them beforehand
> Include RpcPort field in the server status endpoint response

- Arrowgene.Ddon.GameServer/Characters/ExpManager.cs
- Arrowgene.Ddon.GameServer/Characters/QuestManager.cs
- Arrowgene.Ddon.GameServer/Characters/RewardManager.cs
- Arrowgene.Ddon.GameServer/Characters/WalletManager.cs
- Arrowgene.Ddon.GameServer/DdonGameServer.cs
- Arrowgene.Ddon.GameServer/Handler/InstanceEnemyKillHandler.cs
- Arrowgene.Ddon.GameServer/Handler/QuestGetCycleContentsStateListHandler.cs
- Arrowgene.Ddon.GameServer/Quests/GenericQuest.cs
- Arrowgene.Ddon.GameServer/Quests/QuestStateManager.cs
- Arrowgene.Ddon.Server/GameLogicSetting.cs
- Arrowgene.Ddon.Shared/Model/RewardSource.cs
- Added modifiers for gold and rift rewards from quests
- Fixed a bug where JP was not modified correctly for quest rewards.
- Fixed a bug where exp amounts were not displayed correctly in quest amounts.
> enhance: Add new global modifiers

- Arrowgene.Ddon.Database/Arrowgene.Ddon.Database.csproj
- Arrowgene.Ddon.Database/DdonDatabaseBuilder.cs
- Arrowgene.Ddon.Database/Files/Database/Script/migration_scheduling.sql
- Arrowgene.Ddon.Database/Files/Database/Script/schema_sqlite.sql
- Arrowgene.Ddon.Database/IDatabase.cs
- Arrowgene.Ddon.Database/Sql/Core/DdonSqlDbEpitaphRoadClaimedWeeklyRewards.cs
- Arrowgene.Ddon.Database/Sql/Core/DdonSqlDbScheduleNext.cs
- Arrowgene.Ddon.Database/Sql/Core/Migration/00000026_TaskSchedulerMigration.cs
- Arrowgene.Ddon.GameServer/Characters/CharacterManager.cs
- Arrowgene.Ddon.GameServer/Characters/EpitaphRoadManager.cs
- Arrowgene.Ddon.GameServer/Chat/ChatManager.cs
- Arrowgene.Ddon.GameServer/DdonGameServer.cs
- Arrowgene.Ddon.GameServer/RpcManager.cs
- Arrowgene.Ddon.GameServer/ScheduleManager.cs
- Arrowgene.Ddon.GameServer/ServerUtils.cs
- Arrowgene.Ddon.GameServer/Tasks/DailyTask.cs
- Arrowgene.Ddon.GameServer/Tasks/EpitaphSchedulerTask.cs
- Arrowgene.Ddon.GameServer/Tasks/HourlyTask.cs
- Arrowgene.Ddon.GameServer/Tasks/NextTimeAmountTask.cs
- Arrowgene.Ddon.GameServer/Tasks/SchedulerTask.cs
- Arrowgene.Ddon.GameServer/Tasks/WeeklyTask.cs
- Arrowgene.Ddon.GameServer/Utils/DateUtils.cs
- Arrowgene.Ddon.Rpc.Web/Route/Internal/PacketRoute.cs
- Arrowgene.Ddon.Server/GameLogicSetting.cs
- Arrowgene.Ddon.Shared/Model/Rpc/RpcInternalCommand.cs
- Arrowgene.Ddon.Shared/Model/Scheduler/ScheduleInterval.cs
- Arrowgene.Ddon.Shared/Model/Scheduler/SchedulerTaskEntry.cs
- Arrowgene.Ddon.Shared/Model/Scheduler/TaskType.cs
- Arrowgene.Ddon.Test/Database/DatabaseMigratorTest.cs
Implemented a light weight mechanism for scheduling recurring tasks. This can be used to implement, hourly, daily or weekly resets. There is also an intention to use the mechanism to check for seasonal events and turn on/off depending on the date.
Added example of a weekly reset for Epitaph Weekly rewards.
> feat: Implement a generic task scheduler

- Arrowgene.Ddon.GameServer/GatheringItems/InstanceEventDropItemManager.cs
- Arrowgene.Ddon.Shared/Asset/EventDropsAsset.cs
- Arrowgene.Ddon.Shared/AssetReader/EventDropAssetDeserializer.cs
- Arrowgene.Ddon.Shared/Files/Assets/EventDrops.json
- Arrowgene.Ddon.Shared/Model/EventItemConstraint.cs
- Added new EventItemConstraint values
- LessThan
- LessThanOrEqual
- GreaterThan
- GreaterThanOrEqual
- InRange
- Added the ability to define constraints based on enemy level
- If the constraint is 'InRange' the fields 'min_lv' and 'max_lv' are required.
- "requirements": {"enemy_level" : {"constraint": "InRange", "min_lv": x, "max_lv": y}}
- If the constraint is any of the other types the field 'lv' is required.
- "requirements": {"enemy_level" : {"constraint": "LessThan|LessThanOrEqual|GreaterThan|GreaterThanOrEqual", "lv": x}}
- Added the ability to define constraints based on if the enemy is a boss or not.
- "requirements": {"enemy_class": "None|IsBoss|IsNotBoss"}
> feat: Add enemy constraints for event drop systems

- Arrowgene.Ddon.GameServer/BazaarManager.cs
- Arrowgene.Ddon.GameServer/Characters/GpCourseManager.cs
- Arrowgene.Ddon.GameServer/Handler/BazaarGetExhibitPossibleNumHandler.cs
- Arrowgene.Ddon.Server/GameLogicSetting.cs
Adds new game server settings for the bazaar timers BazaarExhibitionTimeSeconds and BazaarCooldownTimeSeconds, with default values of 3 days and 1 day.
Implements the GP course effects that extend bazaar slots and reduces new bazaar cooldown timer
> Configurable bazaar timers and bazaar related GP course effects

- Arrowgene.Ddon.Database/Files/Database/Script/clan_migration.sql
- Arrowgene.Ddon.Database/Files/Database/Script/equip_migration_sqlite.sql
- Arrowgene.Ddon.Database/Files/Database/Script/migration_mail_sqlite.sql
- Arrowgene.Ddon.Database/Files/Database/Script/schema_sqlite.sql
- Arrowgene.Ddon.Database/Sql/Core/DdonSqlDb.cs
- Arrowgene.Ddon.Database/Sql/Core/DdonSqlDbBazaarExhibition.cs
- Arrowgene.Ddon.Database/Sql/Core/DdonSqlDbCharacter.cs
- Arrowgene.Ddon.Database/Sql/Core/DdonSqlDbCharacterCommon.cs
- Arrowgene.Ddon.Database/Sql/Core/DdonSqlDbContactList.cs
- Arrowgene.Ddon.Database/Sql/Core/DdonSqlDbPawn.cs
- Arrowgene.Ddon.Database/Sql/SqlDb.cs
- Arrowgene.Ddon.GameServer/Handler/PawnGetNoraPawnListHandler.cs
- [x ] The project compiles
- [x ] The PR targets `develop` branch
fix some data types and code that dont work on postgres
> Fix postgres

- Arrowgene.Ddon.Shared/Files/Assets/quests/q00020190.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q00020210.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q00020220.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q00020230.json
Fixed an issue where "ReturnCheckPoint" was jumping to an invalid block id for the process.
> fix: Fix issue with MSQ area check

- Arrowgene.Ddon.GameServer/Characters/ExpManager.cs
- Arrowgene.Ddon.GameServer/Handler/InstanceEnemyKillHandler.cs
- Arrowgene.Ddon.GameServer/Quests/Quest.cs
- Arrowgene.Ddon.Server/Scripting/interfaces/GameLogicSetting.cs
- Arrowgene.Ddon.Shared/Files/Assets/scripts/settings/GameLogicSettings.csx
Separate exp modifiers for enemies in and outside of Bitterblack Maze game mode.
Tested settings below:
**EnemyExpModifer: 2.0
BBMEnemyExpModifer: 1.0**
goblin (lv1): 20 exp
Netherworld Familiar (lv8, BBM): 175 exp
A Man Eating Ogre (enemy): 15200 exp
A Man Eating Ogre (Quest): 1020 exp
**EnemyExpModifer: 1.0
BBMEnemyExpModifer: 2.0**
goblin (lv1): 10 exp
Netherworld Familiar (lv8, BBM): 350 exp
A Man Eating Ogre (enemy): 7600 exp
A Man Eating Ogre (Quest): 1020 exp
> Add separate exp modifier for BBM enemies

- docs/quests/endgame_content.md
Created a document which tracks the different endgame contents which are implemented using the quest system. Intended to track which EXMs, Clan Quests and War Missions still need to be implemented.
> docs: Add Quest Endgame Content document

- Arrowgene.Ddon.GameServer/Characters/BitterblackMazeManager.cs
- Arrowgene.Ddon.GameServer/Characters/EpitaphRoadManager.cs
- Arrowgene.Ddon.GameServer/Characters/ItemManager.cs
- Arrowgene.Ddon.GameServer/GatheringItems/Generators/EnemyEpitaphRoadDropGenerator.cs
- Arrowgene.Ddon.GameServer/GatheringItems/Generators/EnemyEventDropGenerator.cs
- Arrowgene.Ddon.GameServer/GatheringItems/InstanceDropItemManager.cs
- Arrowgene.Ddon.GameServer/GatheringItems/InstanceGatheringItemManager.cs
- Arrowgene.Ddon.GameServer/Handler/InstanceGetDropItemListHandler.cs
- Arrowgene.Ddon.GameServer/Handler/InstanceGetGatheringItemListHandler.cs
- Arrowgene.Ddon.GameServer/Handler/QuestGetRewardBoxItemHandler.cs
- Arrowgene.Ddon.GameServer/Quests/Quest.cs
- Arrowgene.Ddon.GameServer/Scripting/Interfaces/IQuest.cs
- Arrowgene.Ddon.Shared/AssetReader/AssetCommonDeserializer.cs
- Arrowgene.Ddon.Shared/AssetReader/EnemySpawnAssetDeserializer.cs
- Arrowgene.Ddon.Shared/AssetReader/QuestAssetDeserializer.cs
- Arrowgene.Ddon.Shared/AssetReader/QuestDropAssetDeserializer.cs
- Arrowgene.Ddon.Shared/Csv/GatheringItemCsv.cs
- Arrowgene.Ddon.Shared/Entity/Structure/CDataRewardBoxItem.cs
- Arrowgene.Ddon.Shared/Entity/Structure/CDataRewardItem.cs
- Arrowgene.Ddon.Shared/Entity/Structure/CDataRewardItemDetail.cs
- Arrowgene.Ddon.Shared/Model/DropsTable.cs
- Arrowgene.Ddon.Shared/Model/GatheringItem.cs
- Arrowgene.Ddon.Shared/Model/InstancedEnemy.cs
- Arrowgene.Ddon.Shared/Model/InstancedGatheringItem.cs
- Arrowgene.Ddon.Shared/Model/Quest/QuestRewards.cs
Added the ability to provide reward items using the ItemId enum instead of numeric literals in quest JSON files.
> quest: Allow ItemId enum for quest files

- Arrowgene.Ddon.GameServer/Handler/QuestSetPriorityQuestHandler.cs
Fixed an issue where $ is printed when printing the quest schedule id during an error message.
> fix: Fix printing $ in error message

- Arrowgene.Ddon.Shared/Files/Assets/quests/q20070001.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20080003.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20085008.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20090001.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20095007.json
Fixes for the following world quests
- The Perilous Labyrinth
- DeadLord Retainer
- Knight Devourer
- Dubious Remedy
Authored-by: Cert
> fix: World Quest Fixes

- Arrowgene.Ddon.Shared/Files/Assets/EpitaphRoad.json
- Arrowgene.Ddon.Shared/Files/Assets/scripts/settings/GameLogicSettings.csx
Fixed an issue in Rathnite Foothills where the green lights in the 4th path of the cave did not work as expected. Enabled the weekly rewards flag so that code can start being exercised for correctness.
> fix: Fix Epitaph Road Green Light

- Arrowgene.Ddon.Shared/Files/Assets/scripts/quests/exm/q50300004.csx
Fixed an issue where the wrong set of time extension monsters was spawned after engaging the final boss.
> fix: Fix issue with spawns in q50300004

- Arrowgene.Ddon.GameServer/Quests/GenericQuest.cs
- Arrowgene.Ddon.GameServer/Quests/QuestBlockUtil.cs
- Arrowgene.Ddon.Server/Scripting/LibUtils.cs
- Arrowgene.Ddon.Shared/Files/Assets/EventDrops.json
- Arrowgene.Ddon.Shared/Files/Assets/scripts/quests/exm/q50300004.csx
- Arrowgene.Ddon.Shared/Files/Assets/scripts/quests/seasonal_events/halloween/2017/q60301000.csx
- Arrowgene.Ddon.Shared/Files/Assets/scripts/quests/seasonal_events/valentines/2017/q60200024.csx
- Arrowgene.Ddon.Shared/Files/Assets/scripts/quests/seasonal_events/valentines/2017/q60200025.csx
- Arrowgene.Ddon.Shared/Files/Assets/scripts/quests/seasonal_events/valentines/2017/q60200026.csx
- Arrowgene.Ddon.Shared/Files/Assets/scripts/settings/SeasonalEvents.csx
- Arrowgene.Ddon.Shared/Model/Quest/QuestBlock.cs
- Arrowgene.Ddon.Shared/Model/Quest/QuestNotifyCommand.cs
- Implemented the 2017 Valentines day seasonal event quests.
- Updated the EventDrops.json to drop Handpicked Cacao when the event is active.
- Added new settings in SeasonalEvents.csx.
- Updated the QuestBlock and QuestBlockUtils class to accept new commands and block types.
- Added new QuestNotifyCommand values.
Co-authored-by: Dixdros
> feat: Valentines Day Seasonal Event

- Arrowgene.Ddon.GameServer/Quests/GenericQuest.cs
- Arrowgene.Ddon.GameServer/Quests/QuestBlockUtil.cs
- Arrowgene.Ddon.GameServer/Scripting/Interfaces/IQuest.cs
- Arrowgene.Ddon.GameServer/Scripting/LibDdon.cs
- Arrowgene.Ddon.Shared/Files/Assets/scripts/quests/exm/q50300005.csx
- Arrowgene.Ddon.Shared/Model/Quest/QuestBlock.cs
- Added a new member to the QuestBlock which a quest can define an arbitrary number of callbacks to be executed at the end of a quest step.
- Added a new function to QuestBlockUtility to make adding the callback easier in quest scripts.
> feat: Add lambda callbacl functions to QuestBlock

- Arrowgene.Ddon.GameServer/Quests/GenericQuest.cs
- Arrowgene.Ddon.GameServer/Quests/Quest.cs
- Arrowgene.Ddon.GameServer/Scripting/Interfaces/IQuest.cs
- Arrowgene.Ddon.GameServer/Scripting/Modules/GameServerScriptModule.cs
- Arrowgene.Ddon.Server/Scripting/LibUtils.cs
- Arrowgene.Ddon.Server/Scripting/ScriptManager.cs
- Arrowgene.Ddon.Server/Scripting/modules/GameServerSettingsModule.cs
- Arrowgene.Ddon.Shared/Asset/QuestAsset.cs
If the build is a debug build, it is possible to debug csx scripts loaded by the server. Fixed an issue where the datetime range compare was incorrect with a period that crosses from one month to the next. Added a new field EnableCancel which can be used by tutorial quests.
> feat: Add support for debugging csx scripts

- Arrowgene.Ddon.Scripts/scripts/area_rank/monster_caution_spots/12_mergoda_ruins/ar04_elixir_refining_chamber.csx
Fixed an issue where a comma was missing in the previous checkin, which causes the script to fail to compile.
> fix: Fix typo in script file

- Arrowgene.Ddon.Database/Files/Database/Script/migration_partner_pawn.sql
- Arrowgene.Ddon.Database/Files/Database/Script/schema_sqlite.sql
fixes postgres issue caused by duplicate private key name
> fixes diplicate private key name

- Arrowgene.Ddon.Database/Sql/Core/DdonSqlDb.cs
- Arrowgene.Ddon.Database/Sql/DdonPostgresDb.cs
- Arrowgene.Ddon.Database/Sql/SqlDb.cs
- Arrowgene.Ddon.Scripts/scripts/libs.csx
fixes issue for postgres where bigint/longs were being cast to doubles
fixes issues for linux where the script compilations could not find any libs
> fixes issues with postgres and linux

- Arrowgene.Ddon.Database/Sql/Core/DdonSqlDbCharacterCommon.cs
Postgres does not support multiple simultaneous operations on the same connection
> yet another fix for postgres

- Arrowgene.Ddon.GameServer/Handler/EquipEnhancedEnhanceItemHandler.cs
Change the order of the item update packet to see if it improves UI on real servers.
> fix: Change order of packets in limit break

- Arrowgene.Ddon.Scripts/scripts/quests/personal/q60300004.csx
- Arrowgene.Ddon.Shared/AssetReader/QuestAssetDeserializer.cs
- Arrowgene.Ddon.Shared/Files/Assets/quests/q00000019.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q00020050.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q00020070.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q00020080.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q00020090.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q00020130.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q00020150.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q00020190.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q00020210.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q00020220.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q00020230.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q00020240.json
- Arrowgene.Ddon.Shared/Model/Quest/QuestFlags.cs
- q60300004.csx: Fixed infinite repeat
- Fixed an issue where the BGM plays after the fight ends until you logged out
- Unlocked the TowerOfIvanos.QuestBoard at the correct time
- Unlocked the following areas 
- Lestania.TempleOfPurificationSouthChamber
- Lestania.KnightsDepotRuins
- FaranaPlains.KingalCanyonBorderCheckpoint
- FaranaPlains.VegasaCorridorSouth
- MorrowForest.VegasaCorridorWest
- FaranaPlains.VegasaCorridorEast
- HollowOfBeginnings.HollowOfBeginningsGatheringArea
- HollowOfBeginnings.ValtableHall
- ValtableHall.ValtableHallUpperArea
> fixes: Fixes for S2 Content

- Arrowgene.Ddon.Shared/Files/Assets/quests/q00020210.json
Fixed an issue where the unlock flag had the wrong area.
> fix: Fix a typo in area unlock

- Arrowgene.Ddon.Shared/Model/Quest/QuestFlags.cs
Fixed issue with Kingal Canyon Border Checkpoint flag.
> fix: Fix issue with flag using wrong quest id

- Arrowgene.Ddon.Shared/Model/Quest/QuestFlags.cs
Fix a few quest IDs for the world quests which seem to work but don't match the pcap values.
> fix: Fix quest ids

- Arrowgene.Ddon.Cli/Command/ClientCommand.cs
- Arrowgene.Ddon.Client/ArcArchive.cs
- Arrowgene.Ddon.Client/GmdPackActions.cs
While DDOn clean files are ARCC with encryption, when someone unpacks and repacks them with ARCtool, they get repacked into an ARC without encryption. With these changes, it's possible for the gmd patcher to handle these unencrypted ARC files.
> Handle unencrypted ARC files
