- Arrowgene.Ddon.Shared/Csv/CsvReader.cs
When reading a CSV header, rather than showing it as an error, it shows as info
> Made CSV header reading error less scary

- Arrowgene.Ddon.GameServer/Handler/WarpGetFavoriteWarpPointListHandler.cs
- Arrowgene.Ddon.GameServer/Handler/WarpGetWarpPointListHandler.cs
cause nep was complaining (not without reason)
> restored all available teleports

- Arrowgene.Ddon.GameServer/DdonGameServer.cs
- Arrowgene.Ddon.GameServer/Handler/CharacterPawnGoldenReviveHandler.cs
- Arrowgene.Ddon.GameServer/Handler/CharacterPawnPointReviveHandler.cs
- Arrowgene.Ddon.Shared/Entity/EntitySerializer.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/C2SCharacterPawnGoldenReviveReq.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/C2SCharacterPawnPointReviveReq.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CCharacterPawnGoldenReviveRes.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CCharacterPawnPointReviveRes.cs
> Add pawn revive handler

- Arrowgene.Ddon.GameServer/Chat/ChatMessage.cs
- Arrowgene.Ddon.GameServer/Chat/ChatResponse.cs
- Arrowgene.Ddon.GameServer/GameRouter.cs
- Arrowgene.Ddon.GameServer/Handler/LobbyLobbyChatMsgHandler.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CLobbyChatMsgNotice.cs
> Fix - Pawn chat log

- README.md
Many aspects of the document are not informative to the user, I request it to improve these things.
That's what I'm requesting.
> Please, this document is very flawed, I had to fix some typo problems.

- deploy/hooks.json
> test webhook

- README.md
> Update README to reflect HTTP port change

- Arrowgene.Ddon.GameServer/Handler/ContextGetSetContextHandler.cs
- Arrowgene.Ddon.GameServer/Handler/PartyPartyCreateHandler.cs
- Arrowgene.Ddon.GameServer/Handler/PartyPartyInviteCharacterHandler.cs
- Arrowgene.Ddon.GameServer/Handler/PartyPartyInviteEntryHandler.cs
- Arrowgene.Ddon.GameServer/Handler/PartyPartyInvitePrepareAcceptHandler.cs
- Arrowgene.Ddon.GameServer/Handler/PartyPartyJoinHandler.cs
- Arrowgene.Ddon.GameServer/Handler/PartyPartyLeaveHandler.cs
- Arrowgene.Ddon.GameServer/Party.cs
- Arrowgene.Ddon.Shared/Entity/EntitySerializer.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/C2SContextGetSetContextReq.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CContextSetContextBaseNtc.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CPartyPartyInvitePrepareAcceptNtc.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CPartyPartyInviteSuccessNtc.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CPartyPartyMemberSessionStatusNtc.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CSetContextNtc.cs
- Arrowgene.Ddon.Shared/Entity/Structure/CDataContextSetAdditional.cs
- Arrowgene.Ddon.Shared/Entity/Structure/CDataContextSetBase.cs
- Arrowgene.Ddon.Shared/Entity/Structure/CDataOcdImmuneLv.cs
- Arrowgene.Ddon.Shared/Network/PacketId.cs
Ability to invite and join parties, being able to play together and fight monsters. Very early in development.
> Early development of coop play

- Arrowgene.Ddon.Database/IDatabase.cs
- Arrowgene.Ddon.Database/Sql/Core/DdonSqlDbCharacter.cs
- Arrowgene.Ddon.Database/Sql/Core/DdonSqlDbSetAcquirementParam.cs
- Arrowgene.Ddon.Database/Sql/SqlDb.cs
- Arrowgene.Ddon.GameServer/Chat/Command/Commands/JobCommand.cs
- Arrowgene.Ddon.GameServer/Handler/JobChangeJobHandler.cs
- Arrowgene.Ddon.GameServer/Handler/JobGetJobChangeListHandler.cs
- Arrowgene.Ddon.GameServer/Handler/SkillChangeExSkillHandler.cs
- Arrowgene.Ddon.GameServer/Handler/SkillSetOffSkillHandler.cs
- Arrowgene.Ddon.GameServer/Handler/SkillSetSkillHandler.cs
- Arrowgene.Ddon.Shared/Entity/EntitySerializer.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CSkillCustomSkillSetNtc.cs
- Arrowgene.Ddon.Shared/Network/PacketId.cs
Job and skill changing operations now modify only the relevant tables and the creation, update and loading of characters and their related data is done in a transaction.
> Database optimizations

- Arrowgene.Ddon.Cli/Command/ServerCommand.cs
- Arrowgene.Ddon.Cli/Setting.cs
- Arrowgene.Ddon.GameServer/GameServerSetting.cs
- Arrowgene.Ddon.LoginServer/Handler/ClientDecideCharacterIdHandler.cs
- Arrowgene.Ddon.LoginServer/LoginServerSetting.cs
- Arrowgene.Ddon.Server/DdonServer.cs
- Arrowgene.Ddon.Server/ServerSetting.cs
- Arrowgene.Ddon.WebServer/DdonWebServer.cs
summary of the change:
- logging for bound ports
- system environment logs
- warning logs
motivation and context:
ease troubleshooting connectivity issues by printing bound interfaces
> logging for bound ports, system environment and warning

- Arrowgene.Ddon.Cli/Program.cs
Please include a summary of the change and which issue is fixed. 
- each log will be written as a new line in the log file
Please also include relevant motivation and context.
- previously log text for file did not include new lines, and text was appending in a single line
- [ x] The project compiles
- [ x] The PR targets `develop` branch
> new lines for logs in logfile

- Arrowgene.Ddon.Cli/Command/ServerCommand.cs
- Arrowgene.Ddon.Rpc.Web/Arrowgene.Ddon.Rpc.Web.csproj
- Arrowgene.Ddon.Test/Arrowgene.Ddon.Test.csproj
- Arrowgene.Ddon.WebServer/Arrowgene.Ddon.WebServer.csproj
- Arrowgene.Ddon.WebServer/DdonWebServer.cs
- Arrowgene.Ddon.WebServer/WebServerSetting.cs
Please include a summary of the change and which issue is fixed. 
- internal web server updated to latest Kestrel version
- print all routes and files that are served / exposed on startup
- ability to bind to specific interface, not just .Any
Please also include relevant motivation and context.
- raise awarenes about what ports are used by the application, and which files are accessable
- [ x] The project compiles
- [ x] The PR targets `develop` branch
> update web server

- Arrowgene.Ddon.GameServer/Handler/SkillSetSkillHandler.cs
> Fixed skills not being saved correctly

- Arrowgene.Ddon.Database/Files/Database/Script/schema_sqlite.sql
- Arrowgene.Ddon.Database/IDatabase.cs
- Arrowgene.Ddon.Database/Sql/Core/DdonSqlDbCharacter.cs
- Arrowgene.Ddon.Database/Sql/Core/DdonSqlDbCommunicationShortcut.cs
- Arrowgene.Ddon.Database/Sql/Core/DdonSqlDbShortcut.cs
- Arrowgene.Ddon.GameServer/Handler/SetCommunicationShortcutHandler.cs
- Arrowgene.Ddon.GameServer/Handler/SetShortcutHandler.cs
- Arrowgene.Ddon.GameServer/Handler/SkillSetAbilityHandler.cs
- Arrowgene.Ddon.Shared/Entity/EntitySerializer.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/C2SSetCommunicationShortcutReq.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/C2SSetShortcutReq.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CSetCommunicationShortcutRes.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CSetShortcutRes.cs
- Arrowgene.Ddon.Shared/Entity/Structure/CDataCommunicationShortCut.cs
- Arrowgene.Ddon.Shared/Entity/Structure/CDataShortCut.cs
- README.md
> Persist shortcuts and comunication shortcuts in DB

- Arrowgene.Ddon.Database/Files/Database/Script/schema_sqlite.sql
- Arrowgene.Ddon.Database/IDatabase.cs
- Arrowgene.Ddon.Database/Sql/Core/DdonSqlDbCommunicationShortcut.cs
- Arrowgene.Ddon.Database/Sql/Core/DdonSqlDbShortcut.cs
Makes saving shortcuts actually work properly
> Fixed terrible choice of primary keys made when sleepy at 1am

- Arrowgene.Ddon.GameServer/GameStructure.cs
- Arrowgene.Ddon.GameServer/Handler/PartyPartyCreateHandler.cs
- Arrowgene.Ddon.GameServer/Handler/PartyPartyInviteCancelHandler.cs
- Arrowgene.Ddon.GameServer/Handler/PartyPartyInviteCharacterHandler.cs
- Arrowgene.Ddon.GameServer/Handler/PartyPartyInviteRefuseHandler.cs
- Arrowgene.Ddon.GameServer/Handler/PartyPartyJoinHandler.cs
- Arrowgene.Ddon.GameServer/Handler/PartyPartyMemberKickHandler.cs
- Arrowgene.Ddon.GameServer/Party/PartyGroup.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CPartyPartyInviteCancelNtc.cs
- Arrowgene.Ddon.Shared/Files/Assets/GameServerList.csv
- fix issue where solo player could not promote themself to leader
- better logging
- change default serverId to 10
> Party refinement

- .vscode/extensions.json
- Arrowgene.Ddon.GameServer/Handler/EquipChangeCharacterEquipHandler.cs
- Arrowgene.Ddon.GameServer/Handler/InstanceGetGatheringItemHandler.cs
- Arrowgene.Ddon.GameServer/Handler/ItemMoveItemHandler.cs
- Arrowgene.Ddon.GameServer/Handler/ItemUseBagItemHandler.cs
> Allow items with duplicate UId

- Arrowgene.Ddon.GameServer/Handler/ItemUseBagItemHandler.cs
> Fixed item bag items not substracting when used

- Arrowgene.Ddon.GameServer/Chat/Command/Commands/JobCommand.cs
- Arrowgene.Ddon.GameServer/Handler/JobChangeJobHandler.cs
> Fixed NPE when changing job to Hunter

- Arrowgene.Ddon.GameServer/Handler/SkillSetOffAbilityHandler.cs
Removing an augment removed all augments for the active job in the database rather than only the selected one
> Fixed removal of an augment removing all augs for that job

- Arrowgene.Ddon.GameServer/Handler/JobChangeJobHandler.cs
> Fixed augs not applying after changing job at the NPC

- Arrowgene.Ddon.GameServer/StageLocationAssetManager.cs
> Reloading of gathering items csv on runtime

- .gitattributes
- Arrowgene.Ddon.Cli/Arrowgene.Ddon.Cli.csproj
- Arrowgene.Ddon.Cli/Command/ServerCommand.cs
- Arrowgene.Ddon.Client/Arrowgene.Ddon.Client.csproj
- Arrowgene.Ddon.Database/Arrowgene.Ddon.Database.csproj
- Arrowgene.Ddon.GameServer/DdonGameServer.cs
- Arrowgene.Ddon.LoginServer/Arrowgene.Ddon.LoginServer.csproj
- Arrowgene.Ddon.LoginServer/DdonLoginServer.cs
- Arrowgene.Ddon.Rpc/Arrowgene.Ddon.Rpc.csproj
- Arrowgene.Ddon.Server/Arrowgene.Ddon.Server.csproj
- Arrowgene.Ddon.Server/DdonServer.cs
- Arrowgene.Ddon.Server/Network/Client.cs
- Arrowgene.Ddon.Server/ServerLogger.cs
- Arrowgene.Ddon.Shared/Arrowgene.Ddon.Shared.csproj
- Arrowgene.Ddon.WebServer/Arrowgene.Ddon.WebServer.csproj
Fixes #104 
needs testing before merge
> update logger, provide config based on namespace

- Arrowgene.Ddon.GameServer/Chat/Command/ChatCommandHandler.cs
- Arrowgene.Ddon.GameServer/Chat/Command/Commands/PartyInviteCommand.cs
- Arrowgene.Ddon.GameServer/GameClientLookup.cs
- Arrowgene.Ddon.GameServer/Party/PartyGroup.cs
Bypasses UI limits on sending party invites,
allowing up to 8 players in a party
> Party invite chat command

- Arrowgene.Ddon.Database/IDatabase.cs
- Arrowgene.Ddon.Database/Sql/Core/DdonSqlDbCharacter.cs
- Arrowgene.Ddon.GameServer/DdonGameServer.cs
- Arrowgene.Ddon.GameServer/Handler/CharacterCharacterPointReviveHandler.cs
- Arrowgene.Ddon.GameServer/Handler/CharacterChargeRevivePointHandler.cs
- Arrowgene.Ddon.GameServer/Handler/CharacterGetReviveChargeableTimeHandler.cs
- Arrowgene.Ddon.GameServer/Handler/PawnGetPartyPawnDataHandler.cs
- Arrowgene.Ddon.Shared/Entity/EntitySerializer.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/C2SCharacterChargeRevivePointReq.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/C2SCharacterGetReviveChargeableTimeReq.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/C2SPawnGetPartyPawnDataReq.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CCharacterChargeRevivePointRes.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CCharacterGetReviveChargeableTimeRes.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CPawnGetPartyPawnDataRes.cs
Pawn profile no longer disconnects you + revival power now working as it did back then
> Pawn profile + Revival power

- Arrowgene.Ddon.GameServer/Handler/CharacterDecideCharacterIdHandler.cs
- Arrowgene.Ddon.LoginServer/Handler/CreateCharacterHandler.cs
- Arrowgene.Ddon.Shared/Entity/Structure/CDataCharacterInfo.cs
- Arrowgene.Ddon.Shared/Model/Character.cs
> fixed Exp bar dissapearing after changing jobs

- Arrowgene.Ddon.GameServer/DdonGameServer.cs
> Fixed null pointer exception when leveling up

- Arrowgene.Ddon.GameServer/Characters/ExpManager.cs
- Arrowgene.Ddon.GameServer/Handler/InstanceEnemyKillHandler.cs
> All party members get Exp/HO/BO

- Arrowgene.Ddon.GameServer/Handler/EquipChangeCharacterEquipHandler.cs
- Arrowgene.Ddon.GameServer/Handler/EquipChangePawnEquipHandler.cs
> Fixed dc when equipping pawn equipment from item bag

- Arrowgene.Ddon.Shared/Model/Storages.cs
> fixed NPE when selling items

- Arrowgene.Ddon.Database/IDatabase.cs
- Arrowgene.Ddon.GameServer/Characters/JobManager.cs
> fixed duplicate skills issues

- .dockerignore
- Arrowgene.Ddon.config.local_dev.json
- Dockerfile
- docker-compose.yml
- Provide a basic multi-stage Docker build.
- In the first stage it makes use of the official image mcr.microsoft.com/dotnet/sdk:6.0 to compile the server in an optimized manner (no debug symbols, release build, no bundling the runtime, linux-x64).
- In the second and final stage it makes use of the official image mcr.microsoft.com/dotnet/aspnet:6.0 to deploy the server.
- A default config JSON is used and adjusted to ensure all servers listen on IP 0.0.0.0.
This should allow enthusiasts to more easily & reproducibly run the server without having all necessary tooling setup (aside from Docker).
Checklist:
> Add a multi-stage Docker build for local development.

- Arrowgene.Ddon.GameServer/Characters/ExpManager.cs
- Arrowgene.Ddon.GameServer/Characters/JobManager.cs
> Fixes regarding EX skills and EXP

- Arrowgene.Ddon.GameServer/Characters/JobManager.cs
> Fixed JP not substracting unlocking secret augs

- Arrowgene.Ddon.Shared/Files/Assets/WarpPoints.csv
> Added all missing warp points to CSV

- Arrowgene.Ddon.GameServer/DdonGameServer.cs
- Arrowgene.Ddon.GameServer/Handler/CharacterPawnPointReviveHandler.cs
- Arrowgene.Ddon.GameServer/Handler/PawnPawnLostHandler.cs
- Arrowgene.Ddon.Shared/Entity/EntitySerializer.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/C2SPawnPawnLostReq.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CCharacterPawnPointReviveRes.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CPawnPawnLostRes.cs
Handle lost pawn request and substract revive points when reviving a dead pawn
> Handlers for pawn death requests

- Arrowgene.Ddon.Cli/Command/PacketCommand.cs
> Adjust CLI packet command to produce human readable timestamps.

- Arrowgene.Ddon.GameServer/Handler/BazaarGetItemInfoHandler.cs
> Fix displayed unit prices in bazaar

- Arrowgene.Ddon.GameServer/GatheringItems/InstancedGatheringItem.cs
- Arrowgene.Ddon.Shared/AssetReader/EnemySpawnAssetDeserializer.cs
- Arrowgene.Ddon.Shared/Csv/GatheringItemCsv.cs
- Arrowgene.Ddon.Shared/Model/GatheringItem.cs
> Support for drop chance

- Arrowgene.Ddon.Shared/Files/Assets/EnemySpawn.json
Every placed enemy has loot tables assigned,
There are some loot tables that I lack data to fill out, but placed on the appropriate enemies anyway, labelled as 
`Monster Name "Inconclusive"` if anyone wants to try to find another source & link it to me 👍 
There are some monsters tables that don't exist yet because they were not placed in the world, that'll be a follow up PR.
I prioritized placed enemies and given the size of the task, figured I should push this before I compare the lists to find the enemies that aren't placed lol
> All Placed Enemies LootTables Applied

- Arrowgene.Ddon.GameServer/Handler/LobbyLobbyDataMsgHandler.cs
Send to another player only when both players are in the same lobby.
When outside the lobby, send only to the other players in the party
> Optimize lobby data broadcasting

- Arrowgene.Ddon.GameServer/Handler/LobbyLobbyDataMsgHandler.cs
> Fixed issues with the new lobby handler

- ReleaseFiles/pack_gmd_english.cmd
> Fixing double ""'s in file paths

- Arrowgene.Ddon.GameServer/Characters/ItemManager.cs
- Arrowgene.Ddon.GameServer/Handler/BazaarProceedsHandler.cs
- Arrowgene.Ddon.GameServer/Handler/CraftStartCraftHandler.cs
- Arrowgene.Ddon.GameServer/Handler/ItemMoveItemHandler.cs
- Arrowgene.Ddon.GameServer/Handler/ShopBuyShopGoodsHandler.cs
- Arrowgene.Ddon.Shared/Model/ClientItemInfo.cs
> Allow multiple stacks of the same item

- Arrowgene.Ddon.GameServer/Characters/ItemManager.cs
Solves the issues described in  #235
> Handle moving and swapping items in storage

- Arrowgene.Ddon.GameServer/Characters/CharacterManager.cs
- Arrowgene.Ddon.GameServer/DdonGameServer.cs
- Arrowgene.Ddon.GameServer/Handler/ConnectionLoginHandler.cs
- Arrowgene.Ddon.LoginServer/Handler/CreateCharacterHandler.cs
Added extended parameters to the pawns in preparation to support dragon force augmentation of pawns.
> feat: Add extended params to pawns

- Arrowgene.Ddon.GameServer/Handler/LobbyLobbyDataMsgHandler.cs
- Arrowgene.Ddon.GameServer/Party/PartyManager.cs
Attempt to resolve an issue where a NPE is hit while iterating over players who are not in a party.
> fix: Fix NPE in LobbyLobbyDataMsgHandler

- Arrowgene.Ddon.GameServer/Handler/ItemConsumeStorageItemHandler.cs
> Handle discarding multiple items

- Arrowgene.Ddon.GameServer/Characters/ItemManager.cs
- Arrowgene.Ddon.GameServer/Handler/InstanceGetGatheringItemListHandler.cs
- Arrowgene.Ddon.GameServer/InstanceAssetManager.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/C2SInstanceGetGatheringItemListReq.cs
> Random chance for gathering items to break

- Arrowgene.Ddon.Cli/Command/PacketCommand.cs
> Add support for packet ID / name filtering to the packet command.

- Arrowgene.Ddon.GameServer/Handler/SkillGetAcquirableAbilityListHandler.cs
Minor mistake preventing most players (approx 3/4) from being able to access the Secret Augments
> Fixes most players not getting access to secretaugs

- Arrowgene.Ddon.GameServer/DdonGameServer.cs
- Arrowgene.Ddon.LoginServer/DdonLoginServer.cs
- Arrowgene.Ddon.Server/DdonServer.cs
- Arrowgene.Ddon.Server/Handler/FallbackHandler.cs
- Arrowgene.Ddon.Server/Network/Consumer.cs
Sends back a response packet with only the "Error" field set to 1 Prevents getting kicked back to the main menu
> Generic fallback handler for unknown requests

- Arrowgene.Ddon.GameServer/Handler/CharacterCharacterGoldenReviveHandler.cs
- Arrowgene.Ddon.GameServer/Handler/CharacterPawnGoldenReviveHandler.cs
- Arrowgene.Ddon.GameServer/Handler/GpGetGpHandler.cs
- Arrowgene.Ddon.Server/Handler/FallbackHandler.cs
- Arrowgene.Ddon.Shared/Entity/EntitySerializer.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/C2SGpGetGpReq.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CGpGetGpRes.cs
> Fix time desync when opening GP shop menus

- Arrowgene.Ddon.Shared/Files/Assets/Shop.json
Added support for 37 npcs to sell items up to Gritten Fort.
> Update Shop.json to be more close to the original game

- Arrowgene.Ddon.Database/Files/Database/Script/schema_sqlite.sql
Fixed schema so it properly generates for postgres
> fix schema so it properly generates for postgres

- Arrowgene.Ddon.Shared/Files/Assets/Shop.json
- Added items to Ophelia Adventure Pass Shop
- Added items to Fabio High Orb Exchange Shop
- Added items for all Season 3 areas.
Areas List: Hidden Village Piremoth, Fort Thines, Rothgill, Bertha's Bandit Group Hideout, Mephite, Eli Guard Tower, Fortress City Megado: Residential Area, Northern Bandit Hideout, Firefall Mountain Campsite
> Update Shop.json Season 3 region.

- Arrowgene.Ddon.Shared/Files/Assets/Shop.json
- Added shop for the WQ "q60200033" - "Summer! Beach festival".
> Update Shop.json to support Breya Coast Summer! Beach festival event.

- Arrowgene.Ddon.GameServer/Characters/EquipManager.cs
- Arrowgene.Ddon.GameServer/Characters/ItemManager.cs
- Arrowgene.Ddon.GameServer/Handler/CraftStartCraftHandler.cs
- Arrowgene.Ddon.GameServer/Handler/EquipChangeCharacterEquipHandler.cs
- Arrowgene.Ddon.GameServer/Handler/EquipChangeCharacterStorageEquipHandler.cs
- Arrowgene.Ddon.GameServer/Handler/EquipChangePawnEquipHandler.cs
- Arrowgene.Ddon.GameServer/Handler/EquipChangePawnStorageEquipHandler.cs
- Arrowgene.Ddon.GameServer/Handler/QuestGetRewardBoxItemHandler.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CItemUpdateCharacterItemNtc.cs
Fixes issues #330, #331 and #332
> Fix item and equipment issues

- Arrowgene.Ddon.Database/Sql/Core/DdonSqlDbBazaarExhibition.cs
Fixes only the first one being retrieved, and sorts them from lowest to highest price
> Fix bazaar listing query issues

- Arrowgene.Ddon.GameServer/BazaarManager.cs
Fixes bug where changing prices would mean you'd get paid the original price when other player buys for the new price
> Fix proceeds not updating on bazaar re-exhibit

- Arrowgene.Ddon.GameServer/Quests/Quest.cs
- Arrowgene.Ddon.Shared/AssetReader/QuestAssetDeserializer.cs
- Arrowgene.Ddon.Shared/Files/Assets/quests/q00000004.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20010000.json
- Fixed an issue with the quest "Beach Bandits" due to a typo.
- Fixed an issue where the step count was incorrect when resuming progress.
> Fix small bugs introduced

- Arrowgene.Ddon.GameServer/DdonGameServer.cs
- Arrowgene.Ddon.GameServer/Handler/QuestCancelHandler.cs
- Arrowgene.Ddon.GameServer/Handler/QuestCancelPriorityQuestHandler.cs
- Arrowgene.Ddon.GameServer/Handler/QuestQuestProgressHandler.cs
- Arrowgene.Ddon.GameServer/Party/PartyQuestState.cs
- Arrowgene.Ddon.Shared/Entity/EntitySerializer.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/C2SQuestQuestCancelReq.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CQuestQuestCancelNtc.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CQuestQuestCancelRes.cs
- Arrowgene.Ddon.Shared/Network/PacketId.cs
Add the ability to cancel quests.
> Quest Cancel Support

- Arrowgene.Ddon.Shared/Files/Assets/quests/q20010002.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20010003.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20010004.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20010005.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20010006.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20010007.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20015000.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20015001.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20015002.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20015003.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20015004.json
> Added Breya Coast world quests

- Arrowgene.Ddon.GameServer/Characters/ItemManager.cs
- Arrowgene.Ddon.GameServer/Handler/PawnCreatePawnHandler.cs
- Arrowgene.Ddon.GameServer/Quests/GenericQuest.cs
- Arrowgene.Ddon.Shared/Model/Storages.cs
- Fixed issue with quests that consume items and a new UID was generated causing a mismatch.
- Fixed an issue with pawn creation where the pawn index was not accounted for.
> Fix issues introduced with UID change

- Arrowgene.Ddon.Cli/Command/ServerCommand.cs
Exits with an error message if the version doesn't match
> Close server if the database version doesn't match the target version

- Arrowgene.Ddon.GameServer/Characters/ExpManager.cs
- Arrowgene.Ddon.GameServer/DdonGameServer.cs
- Arrowgene.Ddon.GameServer/Handler/InstanceEnemyKillHandler.cs
- Arrowgene.Ddon.GameServer/Party/PartyQuestState.cs
Enabled the rookies ring which gives an exp bonus while equipped.
> feat: Enable Rookies Ring

- Arrowgene.Ddon.Shared/Files/Assets/quests/q00000001.json
Updated the quest file NPC text.
Co-authored-by: @Abiorugu
> Update NPC dialogue sequence for MSQ1

- Arrowgene.Ddon.Shared/Files/Assets/quests/q00000006.json
- Changed wolf spawn
Co-authored-by: @abiorugu
> Update MSQ "The Girl in the Forest"

- Arrowgene.Ddon.Shared/Files/Assets/quests/q00000009.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q00000027.json
Updated by @abiorugu
Adds NPCs to battle and changes the names and positions of enemies in "The Assailed Fort"
Changes Chimera's Level and Name in "The Goblin King"
EnemySpawn.Json is being touched in a few places right now, I don't want to add to the pile of changes to merge.
The Goblins in Stage 83 should be Deleted.
> Updates to MSQ "The Assailed Fort" and "The Goblin King"

- Arrowgene.Ddon.Shared/Files/Assets/quests/q20040000.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20040001.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20040002.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20040003.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20040004.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20040005.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20040006.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20040007.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20040008.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20040009.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20045000.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20045001.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20045002.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20045003.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20045004.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20045005.json
Add new world quests for Volden Mines
> Add Volden Mines World Quests

- Arrowgene.Ddon.GameServer/Party/PartyManager.cs
Servers like Dix's exceed the current 100, (almost 300!) using max int value causes no one to be able to join though, so 1000:tm: lol
> Adjust PartyLimit to 1000

- Arrowgene.Ddon.Shared/Files/Assets/quests/q20050000.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20050001.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20050002.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20050003.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20050004.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20050005.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20050006.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20050007.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20050008.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20050009.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20055000.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20055001 Ape One.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20055001 Sphinx one.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20055002.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20055003.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20055004 Redcaps.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20055004 Troll.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20055005.json
> Add Mysree Forest World Quests

- Arrowgene.Ddon.Shared/Files/Assets/quests/q20030000.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20030002.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20030003.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20030004.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20030005.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20030006.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20030007.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20030008.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20035001.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20035002.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20035005.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20035006.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20035007.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20035008.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20035009.json
> Add Dowe Valley World Quests

- Arrowgene.Ddon.Shared/Files/Assets/quests/q20060000.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20060001.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20060002.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20060003.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20065000.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20065001.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20065002.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20065003.json
> Add Mysree Grove WQs

- Arrowgene.Ddon.Shared/Files/Assets/quests/q20020000.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20020001.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20020003.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20020004.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20020005.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20020006.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20020007.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20020008.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20020009.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20020010.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20020011.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20025000.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20025001.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20025003.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20025005.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20025006.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20025007.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20025008.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20025009.json
> Add Betland Plains WQ

- Arrowgene.Ddon.GameServer/Characters/CharacterManager.cs
- Arrowgene.Ddon.GameServer/Handler/CharacterDecideCharacterIdHandler.cs
- Arrowgene.Ddon.GameServer/Handler/ConnectionLoginHandler.cs
- Arrowgene.Ddon.GameServer/Handler/ConnectionMoveInServerHandler.cs
- Arrowgene.Ddon.LoginServer/Handler/ClientLoginHandler.cs
- Arrowgene.Ddon.Shared/Entity/EntitySerializer.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CGPCourseExtendNtc.cs
- Arrowgene.Ddon.Shared/Network/PacketId.cs
This prevents issues when connection to channels other than the main one
> Load all account/character/pawn information and send course notice on connection move in

- Arrowgene.Ddon.GameServer/GameServerSetting.cs
- Arrowgene.Ddon.Server/GameLogicSetting.cs
- Arrowgene.Ddon.Server/ServerSetting.cs
- Arrowgene.Ddon.Test/GameServer/SettingTest.cs
> Prevent custom settings from getting overwritten on deserialization

- Arrowgene.Ddon.Shared/AssetRepository.cs
> Less scary error messages when an AssetRepository reload attempt fails

- Arrowgene.Ddon.GameServer/Handler/PartyPartyInviteCharacterHandler.cs
- Arrowgene.Ddon.GameServer/Handler/PartyPartyInvitePrepareAcceptHandler.cs
- Arrowgene.Ddon.LoginServer/Handler/ClientDecideCharacterIdHandler.cs
> Fix joining parties on servers other than the first in GameServerList

- Arrowgene.Ddon.Shared/Files/Assets/quests/q20100000.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20100001.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20100002.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20100003.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20105000.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20105001.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20105002.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20105003.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20105004.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20105005.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20105006.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20105007.json
Added new quest files Deenan Woods
> Add Deenan Woods WQ

- Arrowgene.Ddon.Shared/Files/Assets/quests/q20070000.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20070001.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20070003.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20070004.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20070005.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20070006.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20075002.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20075003.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20075004.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20075005.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20075006.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20075007.json
> Add Northern Betland Plains WQ

- Arrowgene.Ddon.GameServer/Handler/CharacterGetReviveChargeableTimeHandler.cs
Revert "Setting revival timer to 12:00 AM JST to align with original server."
This reverts commit a78198dbdc9dc338c64eb6b50052c120f2a9acf0.
> Revert PR #466

- Arrowgene.Ddon.GameServer/Handler/CharacterSwitchGameModeHandler.cs
Fixed an issue where the BBM character warp point list was not populated, causing an exception an exception to occur.
> fix: Fix BBM warp point exception

- Arrowgene.Ddon.GameServer/Handler/InstanceEnemyKillHandler.cs
> Item bag on enemy kill hotfix

- Arrowgene.Ddon.GameServer/Characters/ExpManager.cs
- Arrowgene.Ddon.GameServer/Characters/GpCourseManager.cs
- Arrowgene.Ddon.GameServer/DdonGameServer.cs
- Arrowgene.Ddon.GameServer/Handler/CharacterDecideCharacterIdHandler.cs
- Arrowgene.Ddon.GameServer/Handler/ConnectionMoveInServerHandler.cs
- Arrowgene.Ddon.GameServer/Handler/InstanceEnemyKillHandler.cs
- Arrowgene.Ddon.GameServer/Party/PartyQuestState.cs
- Arrowgene.Ddon.LoginServer/Handler/GetCharacterListHandler.cs
- Arrowgene.Ddon.Shared/Entity/EntitySerializer.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CGPCourseStartNtc.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CGpCourseEndNtc.cs
- Arrowgene.Ddon.Shared/Files/Assets/GpCourseInfo.json
- Arrowgene.Ddon.Shared/Model/GPCourseId.cs
- Arrowgene.Ddon.Shared/Model/RewardSource.cs
- Arrowgene.Ddon.Shared/Network/PacketId.cs
Added support for the following course effects
- Player Enemy EXP bonus
- Pawn Enemy EXP bonus
- Player World Quest EXP bonus
https://github.com/user-attachments/assets/59718d14-b834-4e69-9222-91c56f4a7e2b
> feat: Add support for GP course EXP bonus

- .vscode/launch.json
- Arrowgene.Ddon.Database/IDatabase.cs
- Arrowgene.Ddon.Database/Sql/Core/DdonSqlDbPawn.cs
- Arrowgene.Ddon.GameServer/Handler/PawnGetRegisteredPawnListHandler.cs
- Arrowgene.Ddon.Test/Database/DatabaseMigratorTest.cs
> Filter registered pawns directly on the SQL query

- Arrowgene.Ddon.GameServer/DdonGameServer.cs
- Arrowgene.Ddon.GameServer/Handler/QuestGetMobHuntQuestListHandler.cs
- Arrowgene.Ddon.Shared/Entity/EntitySerializer.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/C2SQuestGetMobHuntQuestListReq.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CQuestGetMobHuntQuestListRes.cs
- Arrowgene.Ddon.Shared/Entity/Structure/CDataQuestMobHuntQuestInfo.cs
Add handler to prevent softlock of client when menu option is selected.
> Add handler for Mob Hunt Quest

- Arrowgene.Ddon.Shared/Files/Assets/quests/q20080000.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20080001.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20080002.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20080003.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20080004.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20080005.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20080006.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20080007.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20085000.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20085001.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20085002.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20085003.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20085004.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20085005.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20085006.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20085008.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20085009.json
Added new world quests for eastern zandora
> Add Eastern Zandora WQ

- Arrowgene.Ddon.Shared/Files/Assets/quests/q20090000.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20090001.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20095000.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20095001.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20095002.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20095003.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20095004.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20095007.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20095008.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20095010.json
Added new quests and fixed a couple of existing quests.
> Add Zandora Wastelands World Quests

- Arrowgene.Ddon.GameServer/Characters/ExpManager.cs
- Arrowgene.Ddon.GameServer/Characters/QuestManager.cs
- Arrowgene.Ddon.GameServer/Characters/StageManager.cs
- Arrowgene.Ddon.GameServer/Handler/QuestGetCycleContentsStateListHandler.cs
- Arrowgene.Ddon.GameServer/Handler/QuestGetSetQuestListHandler.cs
- Arrowgene.Ddon.GameServer/Handler/QuestGetTutorialQuestListHandler.cs
- Arrowgene.Ddon.GameServer/Handler/QuestQuestProgressHandler.cs
- Arrowgene.Ddon.GameServer/Quests/GenericQuest.cs
- Arrowgene.Ddon.GameServer/Quests/Quest.cs
- Arrowgene.Ddon.Shared/Asset/QuestAsset.cs
- Arrowgene.Ddon.Shared/AssetReader/QuestAssetDeserializer.cs
- Arrowgene.Ddon.Shared/Entity/EntitySerializer.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CQuestGetTutorialQuestListRes.cs
- Arrowgene.Ddon.Shared/Entity/Structure/CDataTutorialQuestList.cs
- Arrowgene.Ddon.Shared/Entity/Structure/CDataTutorialQuestOrderList.cs
- Arrowgene.Ddon.Shared/Files/Assets/quests/q60000050.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q60200100.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q60300401.json
- Arrowgene.Ddon.Shared/Model/Quest/QuestType.cs
Added support for personal quests.
> feat: Enable personal quests

- Arrowgene.Ddon.Shared/Files/Assets/quests/!BROKEN!q20990002.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20990001.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20990003.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20990004.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20995000.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20995002.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20995004.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20995005.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20995006.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20995007.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20995009.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20995010.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20995011.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21000090.json
> Add Mergoda Ruins World Quests

- Arrowgene.Ddon.GameServer/Characters/QuestManager.cs
- Arrowgene.Ddon.GameServer/Handler/PartyPartyCreateHandler.cs
- Arrowgene.Ddon.GameServer/Handler/QuestGetSetQuestInfoListHandler.cs
- Arrowgene.Ddon.GameServer/Handler/QuestGetSetQuestListHandler.cs
- Arrowgene.Ddon.GameServer/Party/PartyQuestState.cs
- Arrowgene.Ddon.GameServer/Quests/Quest.cs
- Fixed issue with world quests not populating the quest log correctly.
- Fixed issue with quest rewards where invalid quest ids crash the client
> Fix quest bugs

- Arrowgene.Ddon.Shared/Files/Assets/quests/q20050009.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20990001.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20990003.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20990004.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20995000.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20995002.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20995004.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20995005.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20995006.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20995007.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q20995011.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21000090.json
- Added missing area id
- Added infected armor type to monster
> Fix issue with some Mergoda quests

- Arrowgene.Ddon.GameServer/Handler/QuestGetSetQuestListHandler.cs
Fixed an issue where the wrong list was queried for quests.
> fix: Fix issue with world quest fetch

- Arrowgene.Ddon.Shared/Files/Assets/quests/q50201000.json
- Added infection type
- Added named param
> Update "Agent of Corruption (EM5)"

- Arrowgene.Ddon.GameServer/Characters/QuestManager.cs
- Arrowgene.Ddon.GameServer/Handler/QuestGetCycleContentsStateListHandler.cs
- Arrowgene.Ddon.GameServer/Handler/QuestGetQuestCompletedListHandler.cs
- Arrowgene.Ddon.GameServer/Handler/QuestGetTutorialQuestListHandler.cs
- Arrowgene.Ddon.GameServer/Handler/QuestQuestProgressHandler.cs
- Arrowgene.Ddon.Shared/AssetReader/QuestAssetDeserializer.cs
- Arrowgene.Ddon.Shared/Files/Assets/quests/q60000050.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q60200100.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q60300047.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q60300401.json
- Arrowgene.Ddon.Shared/Model/Quest/QuestType.cs
- Added tutorial quest "To the Bitterblack Maze"
- Refactored naming of personal to tutorial quests to more closly match nomenclature of game packets.
> feat: Add tutorial quest "To the Bitterblack Maze"

- Arrowgene.Ddon.GameServer/Characters/BitterblackMazeManager.cs
- Arrowgene.Ddon.GameServer/Handler/QuestGetPriorityQuestHandler.cs
- Arrowgene.Ddon.GameServer/Party/PartyQuestState.cs
- Arrowgene.Ddon.Shared/Asset/BitterblackMazeAsset.cs
- Arrowgene.Ddon.Shared/AssetReader/BitterblackMazeAssetDeserializer.cs
- Arrowgene.Ddon.Shared/Files/Assets/BitterblackMaze.json
- Moved chest trash loot into JSON
- Moved rare chest loot into JSON
- Added the ability to configure the chance of getting jewelry from the boss chest.
- Added the ability to configure the chance of getting rare armor from the boss chest.
- Added the ability to configure the gold, silver and red marks rewarded on each stage clear.
> enhancement: Make BBM loot more configurable

- Arrowgene.Ddon.GameServer/Characters/ExpManager.cs
- Arrowgene.Ddon.GameServer/Party/PartyQuestState.cs
- Arrowgene.Ddon.GameServer/Quests/GenericQuest.cs
- Arrowgene.Ddon.GameServer/Quests/Quest.cs
- Arrowgene.Ddon.Shared/Asset/QuestAsset.cs
- Arrowgene.Ddon.Shared/AssetReader/QuestAssetDeserializer.cs
- Arrowgene.Ddon.Shared/Entity/EntitySerializer.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CJobPawnJobPointNtc.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/S2CUpdateCharacterJobPointNtc.cs
- Arrowgene.Ddon.Shared/Entity/Structure/CDataS2CEquipEnhancedGetPacksResUnk0Unk6.cs
- Arrowgene.Ddon.Shared/Entity/Structure/CDataTimeGainQuestList.cs
- Arrowgene.Ddon.Shared/Model/ExpType.cs
Added the ability for a quest to reward job points.
> [!NOTE]
> The job point reward will only show in the quest UI for EXM.
> feat: Allow quests to reward Job Points

- Arrowgene.Ddon.GameServer/Context/ContextManager.cs
- Arrowgene.Ddon.GameServer/Handler/InstanceExchangeOmInstantKeyValueHandler.cs
- Arrowgene.Ddon.GameServer/Handler/InstanceSetOmInstantKeyValueHandler.cs
- Arrowgene.Ddon.GameServer/Quests/GenericQuest.cs
- Arrowgene.Ddon.GameServer/Quests/Quest.cs
- Arrowgene.Ddon.Shared/Asset/QuestAsset.cs
- Arrowgene.Ddon.Shared/AssetReader/QuestAssetDeserializer.cs
- Arrowgene.Ddon.Shared/Files/Assets/quests/q50300001.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q50303000.json
- Arrowgene.Ddon.Shared/Model/Quest/QuestOmInteractEvent.cs
- Arrowgene.Ddon.Shared/Model/Quest/QuestServerAction.cs
- Added new json "q50303000.json".
- Added a new hook system which can be used to react to set OM instance events.
- Added new JSON parsing for the instance OM hook.
- Fixed an issue with the final CS in "q50300001.json".
> feat: Add new EXM "Flames of Darkness: Restricted Area"

- Arrowgene.Ddon.Shared/Files/Assets/quests/q00020130.json
Fixed issues related to NPCs during the battle.
Authored-by: Abiorugu
> fix: Adjust quest "Straying Power"

- Arrowgene.Ddon.Shared/Files/Assets/quests/q21000006.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21000007.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21000008.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21000009.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21000010.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21000011.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21000023.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21000024.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21000025.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21000035.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21000036.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21000037.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21000046.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21000047.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21000048.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21000049.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21000059.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21000062.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21000073.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21000075.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21000085.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21000087.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21000096.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21000097.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21000099.json
Added new world quests for Bloodbane island
> feat: World Quests for Bloodbane Island

- Arrowgene.Ddon.GameServer/Quests/Quest.cs
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21014000.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21014001.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21014005.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21014006.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21014007.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21014008.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21014009.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21014011.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21014012.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21014014.json
Fix issue with EXM where it crashes.
> feat: Add world quests for Elan Water Grove

- Arrowgene.Ddon.Shared/Files/Assets/quests/q00000022.json
- Despawn barrier after cutscene with Klaus plays.
> fix: Fix issue with barrier in "The Dwellers of the Golden Land"

- Arrowgene.Ddon.Shared/Files/Assets/quests/q00020080.json
Added a checkpoint to the quest progress after completing the boss fight.
> fix: Add missing checkpoint to the quest "A Fresh Incident"

- Arrowgene.Ddon.Shared/Files/Assets/quests/q21015000.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21015003.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21015005.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21015006.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21015007.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21015008.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21015012.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q21015013.json
> feat: Add Farana Plains World Quests

- Arrowgene.Ddon.GameServer/Characters/ExpManager.cs
- Arrowgene.Ddon.GameServer/Characters/RewardManager.cs
- Arrowgene.Ddon.GameServer/Handler/InstanceEnemyKillHandler.cs
- Arrowgene.Ddon.GameServer/Handler/QuestGetCycleContentsStateListHandler.cs
- Arrowgene.Ddon.GameServer/Handler/QuestGetRewardBoxItemHandler.cs
- Arrowgene.Ddon.GameServer/Handler/QuestGetRewardBoxListHandler.cs
- Arrowgene.Ddon.GameServer/Quests/QuestStateManager.cs
- Arrowgene.Ddon.Server/GameLogicSetting.cs
Added the following new configuration settings
- ExpModifier = 1.0
- PpModifier = 1.0
- BoModifier = 1.0
- HoModifier = 1.0
- JpModifier = 1.0
- RewardBoxMax = 100
- QuestOrderMax = 20
Fixed an issue with the reward manager.
> feat: Add new settings to be configured

- Arrowgene.Ddon.Database/IDatabase.cs
- Arrowgene.Ddon.Database/Sql/Core/DdonSqlDbBitterBlackMazeContentTreasure.cs
- Arrowgene.Ddon.Database/Sql/Core/DdonSqlDbBitterBlackMazeRewards.cs
- Arrowgene.Ddon.GameServer/Characters/BitterblackMazeManager.cs
- Arrowgene.Ddon.Test/Database/DatabaseMigratorTest.cs
Fixed an issue where a transaction was not passed into some DB queries which causes a hang.
> fix: Fix DB hang in BBM

- Arrowgene.Ddon.GameServer/Handler/InstanceEnemyKillHandler.cs
- Arrowgene.Ddon.GameServer/Handler/QuestSetPriorityQuestHandler.cs
- Arrowgene.Ddon.Shared/AssetReader/AssetCommonDeserializer.cs
- Arrowgene.Ddon.Shared/AssetReader/EpitaphTrialAssetDeserializer.cs
- Arrowgene.Ddon.Shared/AssetReader/QuestAssetDeserializer.cs
- Arrowgene.Ddon.Shared/AssetRepository.cs
- Arrowgene.Ddon.Shared/Files/Assets/epitaph/rathnite_foothills_section1_1_space_trial1.json
- Arrowgene.Ddon.Shared/Files/Assets/epitaph/rathnite_foothills_section2_1_space_trial1.json
- Fixed an issue where section 1, space 1, trial 1 had wrong objectives.
- Fixed an issue where section 2, space 1, did not repop enemies after killing them.
- Fixed an issue with quest monster drops.
- Fixed a null pointer exception when setting quest priority.
> fixes: Fix reported Epitaph Road issues

- Arrowgene.Ddon.Database/Sql/Core/Migration/00000027_TaskSchedulerMigration.cs
Add file which was renamed but not added in previous merge.
> fix: Commit file that was changed

- Arrowgene.Ddon.Server/Scripting/ScriptManager.cs
Fixed paths to use "/" seperator which is understood on all OS.
> fix: Path fixes for Linux host

- docs/quests/endgame_content.md
Added shorter hyperlink text for the references column.
> docs: Fix formatting in endgame content md

- docs/quests/endgame_content.md
Marked "Battle for Gritten Fort: Recapture Battle" as implemented.
> docs: Update endgame content document

- Arrowgene.Ddon.GameServer/Characters/QuestManager.cs
- Arrowgene.Ddon.GameServer/Handler/QuestQuestProgressHandler.cs
- Arrowgene.Ddon.GameServer/Quests/QuestBlockUtil.cs
- Arrowgene.Ddon.GameServer/Scripting/Interfaces/IQuest.cs
- Arrowgene.Ddon.GameServer/Scripting/LibDdon.cs
- Arrowgene.Ddon.Shared/Files/Assets/quests/q50206000.json
- Arrowgene.Ddon.Shared/Files/Assets/scripts/libs/ExtremeMissionUtils.csx
- Arrowgene.Ddon.Shared/Files/Assets/scripts/quests/exm/q50300004.csx
- Arrowgene.Ddon.Shared/Files/Assets/scripts/quests/exm/q50300005.csx
- Arrowgene.Ddon.Shared/Model/InstancedEnemy.cs
- Arrowgene.Ddon.Shared/Model/InstancedRandomEnemy.cs
- Arrowgene.Ddon.Shared/Model/Quest/QuestEnemyGroup.cs
- Arrowgene.Ddon.Shared/Model/Quest/QuestGeneralAnnounceType.cs
- docs/quests/endgame_content.md
- Added an implementation of the EXM "Crucible of Demons".
- Added + icons to Gritten Fort time enemies.
- Add party in stage checks to prevent desync in "Phindym War
Chronicles".
- Added new InstancedRandomEnemy class and libddon helper function to
use it in scripts.
> feat: Add EXM "Crucible of Demons"

- Arrowgene.Ddon.Shared/Files/Assets/quests/q50300010.json
- Arrowgene.Ddon.Shared/Files/Assets/scripts/quests/exm/q50300004.csx
Fix issue where #include was used instead of #load.
> fix: Fix issue with Gritten Fort script

- Arrowgene.Ddon.Shared/Model/InstancedEnemy.cs
- Arrowgene.Ddon.Shared/Model/InstancedRandomEnemy.cs
Adds a way to add to the drop table(s) of InstancedRandomEnemy objects.
> Add a way to add items to drop table(s) of random enemies

- Arrowgene.Ddon.GameServer/Characters/ItemManager.cs
- Arrowgene.Ddon.GameServer/Handler/DispelExchangeDispelItemHandler.cs
- Arrowgene.Ddon.GameServer/Handler/ItemUseJobItemsHandler.cs
- Arrowgene.Ddon.GameServer/Handler/PartnerPawnPresentForPartnerPawnHandler.cs
- Arrowgene.Ddon.GameServer/Handler/QuestDeliverItemHandler.cs
- Arrowgene.Ddon.Shared/Entity/EntitySerializer.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/C2SItemChangeAttrDiscardReq.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/C2SItemUseJobItemsReq.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/C2SPartnerPawnPresentForPartnerPawnReq.cs
- Arrowgene.Ddon.Shared/Entity/PacketStructure/C2SQuestDeliverItemReq.cs
- Arrowgene.Ddon.Shared/Entity/Structure/CDataGetDispelItem.cs
- Arrowgene.Ddon.Shared/Entity/Structure/CDataItemUIdList.cs
Fixed an issue where the incorrect type was used for one of the fields, resulting in undefined behavior and crashes.
> fix: Fix issue with partner pawn packet

- Arrowgene.Ddon.Shared/Files/Assets/LimitBreak.json
Fixed an issue where most armor was not able to have limit break applied.
> fix: Fix issue with armor limit break

- Arrowgene.Ddon.GameServer/Handler/EquipEnhancedEnhanceItemHandler.cs
- Arrowgene.Ddon.Shared/Asset/LimitBreakAsset.cs
- Arrowgene.Ddon.Shared/AssetReader/LimitBreakAssetReader.cs
- Arrowgene.Ddon.Shared/Files/Assets/LimitBreak.json
Added missing buffs to the limit break system for weapons and armor. Adjusted how to calculate the pity roll for premium currencies.
> Add more buffs to limit break

- Arrowgene.Ddon.Shared/Files/Assets/quests/q00020110.json
- Arrowgene.Ddon.Shared/Files/Assets/quests/q00020140.json
- Arrowgene.Ddon.Shared/Model/Quest/QuestFlags.cs
- docs/quests/known_world_manage_quest_flags.txt
- q00020110.json: Bloodbane Isle Precipice
- q00020140.json: Bloodbane Isle Summit
> fixes: Add more unlocks
